.travis.yml
package-lock.json
package.json
src/tests/CoveoPlatform.spec.ts
webpack.config.js

Also added the project to Snyk.
FYI: Enabled package-lock.json for that repository, this way builds will be :rocket:

Configure Travis CI and improve Webpack production build

---

CODEOWNERS
README.md
src/APICore.ts
src/CoveoPlatform.ts
src/tests/CoveoPlatform.spec.ts

Easier to read the [README file here](https://github.com/coveo/platform-client/blob/add-initial-readme/README.md)

Add initial README file

---

README.md

Demo: https://github.com/coveo/platform-client/blob/add-badges-to-readme/README.md

feat: add badges in the README

---

src/resources/BaseInterfaces.ts
src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/Interfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts

Part of https://github.com/coveo/platform-client/pull/6
Unit tested the Catalog resource. I really like how easy it is to test resources :rocket:

Catalog resource unit tests

---

src/resources/BaseInterfaces.ts
src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/Interfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts
src/resources/tests/Resources.spec.ts
src/tests/CoveoPlatform.spec.ts

Part of https://github.com/coveo/platform-client/pull/6

Resources unit tests

---

src/APICore.ts
src/resources/BaseInterfaces.ts
src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/Interfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts
src/resources/tests/Resources.spec.ts
src/tests/APICore.spec.ts
src/tests/CoveoPlatform.spec.ts

part of https://github.com/coveo/platform-client/pull/6

API core unit tests

---

src/APICore.ts
src/CoveoPlatform.ts
src/resources/BaseInterfaces.ts
src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/Interfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts
src/resources/Resources.ts
src/resources/tests/Resources.spec.ts
src/tests/APICore.spec.ts
src/tests/CoveoPlatform.spec.ts

This feature will have multiple PRs that will all merge into this one before being merged into master:

Improve test coverage

---

src/resources/AWS/AWS.ts
src/resources/AWS/AWSInterfaces.ts
src/resources/AWS/index.ts
src/resources/AWS/tests/AWS.spec.ts
src/resources/PlatformResources.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

Also add missing test for the clusters

feat(aws): Add AWS agents resource

---

src/resources/PlatformResources.ts
src/resources/tests/PlatformResources.spec.ts

:shame: forgot to properly export the SecurityCache calls from PlatformRessources.ts

fix(platformressources.ts): export the SecurityCache calls

---

src/APICore.ts
src/resources/Clusters/Cluster.ts
src/resources/Clusters/Nodes/ClusterNode.ts
src/resources/Clusters/Nodes/tests/ClusterNode.spec.ts
src/resources/Clusters/tests/Clusters.spec.ts
src/resources/Organizations/Organization.ts
src/resources/Organizations/tests/Organizations.spec.ts
src/resources/SecurityCache/SecurityCache.ts
src/resources/SecurityCache/tests/SecurityCache.spec.ts

Remove usage of the method with an empty body. 
Adapt unit tests.

style: add a default value to the body parameter of api.post

---

src/resources/PlatformResources.ts

Small update to this branch: Changed the accessing keyword to match others and consistent accessibility.

fix(component): changed Indexes keyword for Index

---

src/resources/Indexes/Indexes.ts
src/resources/Indexes/IndexesInterface.ts
src/resources/Indexes/tests/Indexes.spec.ts

Added ability to make calls for EditJason and getJason, as well as 'apply to all' Indexes. Including UTs

Add indexes interface attributes

---

src/resources/Catalogs/CatalogInterfaces.ts

I ran all the tests and nothing broke 
👈👀👈

Add scope to the CatalogModel interface

---

src/resources/Catalogs/CatalogInterfaces.ts

Seems the scope was not properly modeled.

fix: adding scope model [COM-108]

---

src/resources/PlatformResources.ts
src/resources/Sources/Sources.ts
src/resources/Sources/index.ts
src/resources/Sources/tests/Sources.spec.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

Related to:
https://bitbucket.org/coveord/jsadmin-v2/pull-requests/2053/feature-adui-4882-refactor-source-mappings/diff
https://coveord.atlassian.net/browse/ADUI-4882

feat(sources): add item types resource

---

src/resources/Groups/Groups.ts
src/resources/Groups/GroupsInterfaces.ts
src/resources/Groups/Realms/GroupRealm.ts
src/resources/Groups/Realms/GroupRealmInterfaces.ts
src/resources/Groups/Realms/index.ts
src/resources/Groups/Realms/tests/GroupRealm.spec.ts
src/resources/Groups/index.ts
src/resources/Groups/tests/Groups.spec.ts

https://platformdev.cloud.coveo.com/docs/?api=AuthorizationServer#/Group32Realms

feat(group): add realm resource

---

src/resources/Groups/Groups.ts
src/resources/Groups/GroupsInterfaces.ts
src/resources/Groups/Members/GroupMember.ts
src/resources/Groups/Members/GroupMemberInterfaces.ts
src/resources/Groups/Members/index.ts
src/resources/Groups/Members/tests/GroupMember.spec.ts
src/resources/Groups/index.ts
src/resources/Groups/tests/Groups.spec.ts

https://platformdev.cloud.coveo.com/docs/?api=AuthorizationServer#/Group32Members

feat(group): add members resource

---

src/resources/Groups/Groups.ts
src/resources/Groups/GroupsInterfaces.ts
src/resources/Groups/Invites/GroupInvite.ts
src/resources/Groups/Invites/GroupInviteInterfaces.ts
src/resources/Groups/Invites/index.ts
src/resources/Groups/Invites/tests/GroupInvite.spec.ts
src/resources/Groups/index.ts
src/resources/Groups/tests/Groups.spec.ts

https://platformdev.cloud.coveo.com/docs/?api=AuthorizationServer#/Group32Invites

feat(group): add invite resource

---

src/resources/Groups/Invites/GroupInviteInterfaces.ts
src/resources/Groups/Members/GroupMemberInterfaces.ts

Those wrong imports are preventing master from releasing a new version :bear:

build: fix wrong import of the AuthProvider

---

src/resources/PlatformResources.ts
src/resources/Saml/Saml.ts
src/resources/Saml/SamlInterfaces.ts
src/resources/Saml/index.ts
src/resources/Saml/tests/Saml.spec.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

https://platformdev.cloud.coveo.com/docs/?api=AuthorizationServer#/Saml32Identity32Providers

feat(saml): add the new resource

---

src/resources/MachineLearning/Models/Models.ts

fix(ml-models): corrected the get call response type

---

src/resources/SecurityCache/SecurityCache.ts
src/resources/SecurityCache/tests/SecurityCache.spec.ts

feat(security cache): added identity refresh call

---

src/resources/Search/Search.ts

fix(search api ressource): fix  the base path

---

src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/PipelinesInterfaces.ts
src/resources/Pipelines/tests/Pipelines.spec.ts

making the PR again because github didn't acutally merge my code into master yesterday :confused:

Adui 5226/add pipelines calls

---

src/resources/Pipelines/Pipelines.ts

fix(pipeline): fix pipeline.update return type

---

src/resources/Enums.ts
src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts

fix(update-result-ranking): add kind

---

src/resources/Enums.ts
src/resources/Pipelines/index.ts
src/resources/Search/Search.ts
src/resources/Search/test/Search.spec.ts

feat(search-query): add query call

---

src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/tests/Pipelines.spec.ts

fix(result-ranking): import result ranking

---

src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts

fix(result-ranking): result-ranking-condition

---

src/resources/Sources/Sources.ts
src/resources/Sources/SourcesFields/SourcesFields.ts
src/resources/Sources/SourcesFields/SourcesFieldsInterfaces.ts
src/resources/Sources/SourcesFields/index.ts
src/resources/Sources/SourcesFields/tests/SourcesFields.spec.ts
src/resources/Sources/index.ts

We'll need these calls for refactoring Fields.

feat(sources): add sources fields calls

---

src/resources/Pipelines/ResultRankings/ResultRankings.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts

Update interface for the update and create

fix(result-ranking): wrong interface

---

src/resources/Pipelines/Conditions/Condition.ts
src/resources/Pipelines/Conditions/ConditionInterfaces.ts
src/resources/Pipelines/Conditions/index.ts
src/resources/Pipelines/Conditions/tests/Condition.spec.ts
src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/PipelinesInterfaces.ts
src/resources/Pipelines/Statements/StatementsInterfaces.ts
src/resources/Pipelines/index.ts

https://platform.cloud.coveo.com/docs?api=SearchApi#!/Pipelines32V1/post_rest_search_v1_admin_pipelines_statements

feat(conditions): implement the condition resource calls

---

src/resources/Pipelines/ResultRankings/ResultRankings.ts

update return for the get and update

fix(result-ranking): api change

---

src/resources/Enums.ts
src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/StatementGroups/StatementGroups.ts
src/resources/Pipelines/StatementGroups/StatementGroupsInterfaces.ts
src/resources/Pipelines/StatementGroups/index.ts
src/resources/Pipelines/StatementGroups/tests/StatementGroups.spec.ts
src/resources/Pipelines/index.ts

https://platformdev.cloud.coveo.com/docs?api=SearchApi#!/Pipelines32V2/get_rest_search_v2_admin_pipelines_pipelineId_statementGroups
We might need to add more properties to the StatementGroupModel later.

Add StatementGroups resource to Pipelines

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

Allow the generation of a presigned url for a snapshot

feat(resourcesnapshot): add GenerateSnapshotUrl call to ResourceSnapshot

---

src/resources/Pipelines/StatementGroups/StatementGroups.ts
src/resources/Pipelines/StatementGroups/tests/StatementGroups.spec.ts

feat(statementgroups): new calls

---

README.md
src/APICore.ts
src/ConfigurationInterfaces.ts
src/Endpoints.ts
src/Entry.ts
src/Errors.ts
src/PlatformClient.ts
src/tests/APICore.spec.ts
src/tests/PlatformClient.spec.ts
src/utils/Retriever.ts
src/utils/index.ts
src/utils/tests/Retriever.spec.ts

I did some refactoring so that multi-region support will be easier to implement. Everything looks cleaner now, but I had to do some minor breaking changes which are all identified in the commit messages and will be published in the changeslog.
PS: the readme diff is easier to review from [the actual readme file](https://github.com/coveo/platform-client/blob/streamlined-options/README.md)

Paving the way for multi-region support

---

src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts

add new param in result ranking to set or get the new group id

feat(group): result ranking group

---

src/APICore.ts
src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts
src/tests/APICore.spec.ts

- Allow custom url to be used by fetch
- Added getContent to resource snapshot

Feature/src 3709 Add custom url and getSnapshotContent

---

src/resources/PlatformResources.ts
src/resources/UsageAnalytics/Read/Statistics/Statistics.ts
src/resources/UsageAnalytics/Read/Statistics/StatisticsInterfaces.ts
src/resources/UsageAnalytics/Read/Statistics/index.ts
src/resources/UsageAnalytics/Read/Statistics/tests/Statistics.spec.ts
src/resources/UsageAnalytics/UsageAnalytics.ts
src/resources/UsageAnalytics/index.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

added the /v15/stats/ calls (read) from ua with UTs for AB Test

feat(/usageanalytics): added the calls from statistics (Read)

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

feat(resourcesnapshots): adding dryrun call

---

src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts

update interface for group in result ranking object

fix(groups): result ranking

---

src/resources/Enums.ts

Simply to add an Enum value into the ModelStatus so I can work further on the case ADUI-5494.

feat(pipelines): add a new enum for the ModelStatus

---

jest.setup.ts
package-lock.json
package.json
src/resources/Fields/tests/Fields.spec.ts
src/resources/Organizations/tests/Organizations.spec.ts
src/resources/Resource.ts
src/resources/UsageAnalytics/Read/Statistics/Statistics.ts
src/resources/UsageAnalytics/Read/Statistics/tests/Statistics.spec.ts
src/resources/tests/Resource.spec.ts

add the library that handle request with array as queryParams and changed the unit test accordingly

refactor(resource.ts and tests): add query-string package for platform

---

src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts

add associatedGroup returned when we get only 1 group

fix(group): result-ranking

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

Add an api call that validates the file type before sending the file to the backend service

feat(resourcesnapshot): add createFromFile Api Call

---

src/resources/Enums.ts
src/resources/PlatformResources.ts
src/resources/RegionConfigurations/RegionConfiguration.ts
src/resources/RegionConfigurations/RegionConfigurationInterfaces.ts
src/resources/RegionConfigurations/index.ts
src/resources/RegionConfigurations/tests/RegionConfiguration.spec.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

https://platformdev.cloud.coveo.com/docs/?api=Organization#/Region32Configuration

feat(region): add region configuration calls

---

README.md

docs(readme): fix npm badge url

---

package-lock.json
package.json

Linked it to the admin and everything works fine.

chore: update dependencies versions

---

src/resources/MachineLearning/DNEConfiguration/DNEConfiguration.ts
src/resources/MachineLearning/MachineLearning.ts

`platform.ml.dneConfiguration.listFields` returns a PageModel

fix(dneconfiguration): listFields returns a PageModel

---

src/resources/CaseAssistConfigs/CaseAssistConfig.ts

"items" -> "configurations"
Fixing a mistake I made the first time around.

feat(caseassist): changed page model key

---

src/resources/SecurityCache/SecurityCacheInterfaces.ts

Updating interface for SecurityProviderStatisticsModel

fix(securityproviderstatsticsmodel): interface update

---

src/resources/Enums.ts
src/resources/Pipelines/MLAssociations/MLAssociationsInterfaces.ts

add modelEngine
add Enum for Association model types

fix(update): ml association interface

---

src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts

Reverts coveo/platform-client#165
It breaks everything in QA

Revert "feat(catalog): remove fields from catalog creation"

---

src/resources/Pipelines/FacetStateRules/FacetStateRules.ts

fix(facet state rules): typo in url

---

src/resources/Pipelines/FacetStateRules/FacetStateRules.ts

This is getting really embarassing.

fix(facet state rule): missing v2 in url

---

src/resources/SchemaService/SchemaService.ts
src/resources/SchemaService/SchemaServiceInterfaces.ts
src/resources/SchemaService/test/SchemaService.spec.ts

feat: add crud routes to SchemaService

---

src/resources/Enums.ts

feat(result-ranking): new feature

---

src/resources/Pipelines/ResultRankings/ResultRankings.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts

add put to save json
add post to create json

feat(json): put and post

---

src/resources/SchemaService/SchemaServiceInterfaces.ts
src/resources/SchemaService/test/SchemaService.spec.ts

Pretty simple PR, replaced the usage if instanceId with instanceUrl to match the changes in the schema service!
SNOW-417

feat(schemaservice): servicenow instanceurl

---

src/resources/CaseAssistConfigs/CaseAssistConfigInterfaces.ts
src/resources/CaseAssistConfigs/tests/CaseAssistConfig.spec.ts

We have made breaking changes in SVCAPI-134 top the list all configuration return schema and parameters.
Will need to merge once the new version of the service is deployed.

feat(customerserviceapi): update list call schema

---

src/resources/Pipelines/Conditions/Condition.ts
src/resources/Pipelines/Conditions/tests/Condition.spec.ts
src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/tests/Pipelines.spec.ts

revert to v1 for api calls except for statements

fix(pipelines): revert to v1

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

add 2 snapshot result report result codes to ResourceSnapshotsReportResultCode

feat: add items to ResourceSnapshotsReportResultCode

---

package-lock.json
package.json
src/resources/MachineLearning/Models/ModelsInterfaces.ts

for performance reasons, 
lets us remove a consuming call to /models/details in modelsTable.tsx

feat(modelsinterface): +modelSizeStatistic field on MlModel

---

src/resources/Pipelines/Statements/Statements.ts

statement do not exist in v2 api
https://platformdev.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Pipelines%20V1

fix(statements): url version

---

src/resources/Pipelines/Statements/Statements.ts

This reverts commit 9936f6f47d2c3fa217b55485a539025a38c0537a, reversing
changes made to d7e742d3796f2878cf62db1f5d0e7ee87125f8e9.

Revert "Merge pull request #193 from coveo/fix-statements-calls"

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

[SRC-4003]
[SRC-4003]: https://coveord.atlassian.net/browse/SRC-4003

adding query param to export from organization call

---

src/resources/Limits/Limits.ts
src/resources/Limits/LimitsInterfaces.ts
src/resources/Limits/index.ts
src/resources/Limits/tests/Limits.spec.ts
src/resources/PlatformResources.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

feat(limits): add limits

---

.eslintignore
.eslintrc.js
.prettierignore
Jenkinsfile.groovy
package-lock.json
package.json
tsconfig.eslint.json

- Removed the commit analysis check when building the master branch
- Removed some unnecessary linting during our build process

Fix build process

---

Jenkinsfile.groovy

This step was required in react-vapor, but not in the platform-client as jenkins itself don't
trigger builds when releasing a version.

ci(jenkins): remove unnecessary "skip" stage

---

src/resources/Pipelines/MLAssociations/MLAssociations.ts
src/resources/Pipelines/MLAssociations/tests/MLAssociations.spec.ts
src/resources/SecurityCache/SecurityCache.ts
src/resources/SecurityCache/SecurityCacheInterfaces.ts
src/resources/SecurityCache/tests/SecurityCache.spec.ts
src/resources/Sources/SourcesFields/SourcesFields.ts
src/resources/Sources/SourcesFields/tests/SourcesFields.spec.ts

- Add `Platform.sercurityCache.listChildren` & `Platform.securityCache.listParents`
- Remove circular dependencies

Add security cache relationships calls

---

src/resources/Notification/Subscription/Subscription.ts

fix(notification): return statement missing in calls

---

src/resources/PlatformResources.ts
src/resources/tests/PlatformResources.spec.ts

[COM-702]
Well.. :sweat:  I messed up a bit
[COM-702]: https://coveord.atlassian.net/browse/COM-702

feat(catalogconfiguration): remove s from resource name

---

src/resources/Notification/Subscription/SubscriptionInterfaces.ts
src/resources/Notification/Subscription/tests/subscription.spec.ts

fix(notification ressource): typo in SubscriptionPatternModel interface

---

src/resources/Limits/Limits.ts
src/resources/Limits/LimitsInterfaces.ts

the return type was wrong leading to an error in admin-ui implementation

fix(limits): fixed return type for allLimits

---

src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts

fix(search): make the search interfaces match the documentation

---

src/resources/Enums.ts

I added those two options (UrlMatch and UrlDoesNotMatch) to the Admin UI backbone, but it also needs to be added to the new React component. This enum needed to be updated first.
Jira: https://coveord.atlassian.net/browse/CT-7402
related to https://coveord.atlassian.net/browse/CT-7265

feat(failed-auth): added urlmatch and urldoesnotmatch options

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

* new contentSummary attribute, data is in the form {resourceType1: nbOfResources, resourceType2: nbOfResources}
* removed duplicated  ApplyOptions export (pretty sure that's redundant?)

feat(new contentsummary in the resourcesnapshotsmodel): content summary

---

src/resources/PlatformResources.ts

Missing Resource in PlatformResources to be available on the client

feat(adding links to resources): adding links to resources in the platfo

---

src/resources/Catalogs/CatalogInterfaces.ts

[COM-785]
[COM-785]: https://coveord.atlassian.net/browse/COM-785

feat(catalog): add associated catalog to configuration

---

package-lock.json
package.json
src/APICore.ts
src/tests/APICore.spec.ts

Uses https://github.com/coveooss/exponential-backoff , which we currently use heavily in production for other stuff.
https://coveord.atlassian.net/browse/CDX-59

feat(api): retry on platform throttle

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

added options for contentType
J:SRC-4134

feat(resourcesnapshots): added options for contentType

---

src/resources/License/License.ts
src/resources/License/tests/License.spec.ts

feat(license): adapt call to generic endpoint

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

fix(resourcesnapshot): adding required parentResourceType attribute

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

Added Mapping type now that it is supported by the backend

feat(snapshot resource types): added Mapping type

---

src/resources/SchemaService/SchemaServiceInterfaces.ts

Updates to the Schema Service Interfaces to reflect changes to the Schema Service API (displayName was added [here](https://github.com/coveo/schema-service/pull/444)).
WORK-8

feat(schema update)!: update schemaservice interface

---

src/resources/Connectivity/Connectivity.ts
src/resources/Connectivity/ConnectivityInterface.ts
src/resources/Connectivity/tests/Connectivity.spec.ts

We changed the way our api work

feat(connectivity): change api path

---

src/resources/Enums.ts
src/resources/Pipelines/ResultRankings/ResultRankings.ts
src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts

Add the missing ruleTypes and ruleStatuses to the ResultRanking parameters
https://coveord.atlassian.net/browse/SEARCHAPI-5699

feat(result-rankings): add list result-rankings parameters

---

src/resources/Sources/Sources.ts
src/resources/Sources/SourcesFields/SourcesFieldsInterfaces.ts
src/resources/Sources/SourcesInterfaces.ts
src/resources/Sources/SourcesMappings/SourcesMappings.ts
src/resources/Sources/SourcesMappings/SourcesMappingsInterfaces.ts
src/resources/Sources/SourcesMappings/index.ts
src/resources/Sources/SourcesMappings/tests/SourcesMappings.spec.ts

Source mappings can now be read, created, and updated for sources

feat(source mappings): source mappings support for get/update

---

src/resources/SchemaService/SchemaService.ts
src/resources/SchemaService/SchemaServiceInterfaces.ts
src/resources/SchemaService/test/SchemaService.spec.ts

New `interface`s to reflect updates to the `schema-service` !

Feat work 106 schema service objects

---

src/resources/Catalogs/CatalogInterfaces.ts

Added filter parameter to catalog list options.
Related to : https://github.com/coveo/admin-ui/pull/2036

feat(catalog): added filter parameter to catalog list options

---

src/resources/Enums.ts
src/resources/UsageAnalytics/Read/Exports/Exports.ts
src/resources/UsageAnalytics/Read/Exports/ExportsInterfaces.ts
src/resources/UsageAnalytics/Read/Exports/index.ts
src/resources/UsageAnalytics/Read/Exports/tests/Exports.spec.ts
src/resources/UsageAnalytics/Read/index.ts
src/resources/UsageAnalytics/UsageAnalytics.ts

Implement calls used in Data Exports: https://platformdev.cloud.coveo.com/docs/?urls.primaryName=Usage%20Analytics%20Read#/Exports%20API%20-%20Version%2015
Schedules calls will be added in another user story.

feat(ua): add exports resource

---

src/resources/SchemaService/SchemaServiceInterfaces.ts

https://coveord.atlassian.net/browse/SNOW-562
Just a new field in Schema fields, not much else !
Related `schema-service` PR: https://github.com/coveo/schema-service/pull/459

SNOW-562 Feature: add isAlwaysIndexed flag to Schema fields

---

src/resources/SchemaService/SchemaServiceInterfaces.ts
src/resources/SchemaService/test/SchemaService.spec.ts

[SNOW-510](https://coveord.atlassian.net/browse/SNOW-510)
This update adds a missing field that is served by the schema-service

SNOW-510: Add entitiesCount to Schema Service interface

---

src/resources/UsageAnalytics/Read/Snowflake/Snowflake.ts
src/resources/UsageAnalytics/Read/Snowflake/SnowflakeInterfaces.ts
src/resources/UsageAnalytics/Read/Snowflake/index.ts
src/resources/UsageAnalytics/Read/Snowflake/tests/Snowflake.spec.ts
src/resources/UsageAnalytics/Read/index.ts
src/resources/UsageAnalytics/UsageAnalytics.ts
src/resources/UsageAnalytics/tests/UsageAnalytics.spec.ts

Related calls are not documented in Swagger at this moment, please check screenshots shared by @jmprovencher in the Slack channel, thanks!

feat(ua): add snowflake resource

---

src/resources/ModifierTemplates/ModifierTemplateInterfaces.ts
src/resources/ModifierTemplates/ModifierTemplates.ts
src/resources/ModifierTemplates/index.ts
src/resources/ModifierTemplates/tests/ModifierTemplates.spec.ts
src/resources/Organizations/Organization.ts
src/resources/Organizations/OrganizationInterfaces.ts
src/resources/Organizations/tests/Organizations.spec.ts
src/resources/PlatformResources.ts

added definition & modifier resources
FOUND-3515
Copy of https://github.com/coveo/platform-client/pull/291

feat(orgdefinitions): added definition & modifier resources

---

src/resources/Enums.ts

fix(reports): report types are capitalized as expected by API

---

src/resources/UsageAnalytics/Read/Dimensions/Dimensions.ts
src/resources/UsageAnalytics/Read/Dimensions/DimensionsInterfaces.ts
src/resources/UsageAnalytics/Read/Dimensions/tests/Dimensions.spec.ts

BREAKING CHANGE: parameters for createCustomDimension are no longer optional and require name
#300

fix(dimensions): dimension name field is required for dimension creation

---

.github/pull_request_template.md

Added a PR template that points out the recurring mistakes so that we see them less often in reviews.

chore(github): add PR template

---

src/resources/Enums.ts
src/resources/UsageAnalytics/Read/Snowflake/Snowflake.ts
src/resources/UsageAnalytics/Read/Snowflake/SnowflakeInterfaces.ts
src/resources/UsageAnalytics/Read/Snowflake/tests/Snowflake.spec.ts

feat(snowflake): +get and put call for snowflakereaderaccount

---

src/resources/InProductExperiences/InProductExperiences.ts
src/resources/InProductExperiences/InProductExperiencesInterfaces.ts
src/resources/InProductExperiences/index.ts
src/resources/InProductExperiences/tests/InProductExperiences.spec.ts
src/resources/PlatformResources.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

feat(ipx): support for In-Product Experience (IPX)

---

src/resources/UsageAnalytics/Read/Snowflake/Snowflake.ts
src/resources/UsageAnalytics/Read/Snowflake/SnowflakeInterfaces.ts
src/resources/UsageAnalytics/Read/Snowflake/tests/Snowflake.spec.ts

- Adding endpoint to retrieve the reader account endpoint.

feat(adding request for reader account endpoint): reader account endpoi

---

src/resources/PlatformResources.ts

fix(platformresources): +searchusagemetrics key

---

src/resources/Organizations/Members/Members.ts

fix(members.ts): sorry. bad baseurl. should work now

---

src/resources/Enums.ts

fix(authprovider): removed other value

---

src/resources/UsageAnalytics/Read/Reports/ReportsInterfaces.ts

docs(reports): update comment style to enable jsdocs in intellisense

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

Adding report interfaces based on the [API response schema](https://docs.coveo.com/en/3432/cloud-v2-api-reference/migration-api#operation/dryrunUsingPUT_2)

feat(resource snapshots): add report interfaces

---

src/resources/ApiKeys/ApiKeysInterfaces.ts

Added last used date to the api key model interfaces.

feat(apikeys): add lastUsedDate

---

src/resources/Indexes/IndexesInterface.ts
src/resources/Indexes/tests/Indexes.spec.ts

feat(indexes): interface update

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

This reverts commit 397a2f1b792f8cd6ccff2d2b80e3ac44f6eede6e.
This commit is breaking and should be treated accordingly

Revert "fix!: remove unsupported resource types (#351)"

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

BREAKING CHANGE: changing the interface name is breaking
See that PR description https://github.com/coveo/platform-client/pull/351

fix(snapshots): remove unsupported interface

---

src/resources/UsageAnalytics/Read/Dimensions/DimensionsInterfaces.ts
src/resources/UsageAnalytics/Read/Dimensions/tests/Dimensions.spec.ts

!--
If a new Resource class was created in this PR, have you done the following?
- Instantiated the new resource somewhere
- either on the base [PlatformResource class](https://github.com/coveo/platform-client/blob/master/src/resources/PlatformResources.ts)
- or on another resource
- Exported the class and its interfaces so that they are reachable from the [Entry file](https://github.com/coveo/platform-client/blob/master/src/Entry.ts)
-->
this paramter is needed for semi structured custom dimension new feature
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) …

feat(dimensioninterface): +path parameter

---

src/resources/UsageAnalytics/Read/Dimensions/DimensionsInterfaces.ts

path attribute is needed to the dimensionModal for the new semistructured custom dimension feature

feat: 🎸 +path field in dimensionmodal

---

src/resources/Sources/SourcesDatasets/tests/SourcesDatasets.spec.ts

Sorry, I merged my last pr in haste, and shamlessly broke the master build. :shame:

fix(datasets): broken test

---

Jenkinsfile.groovy

Reverts coveo/platform-client#386

Revert "ci: fix the git credentials"

---

Jenkinsfile.groovy

Trying to fix the publish step on the build

ci: fix the git credentials

---

src/resources/Enums.ts

Added missing value in the FieldType enum

feat: add missing FieldType enum value for vector

---

src/resources/Sources/SourcesSubInterfaces/Information.ts

Story: https://coveord.atlassian.net/browse/SRC-4641
There were small errors in this [pull request](https://github.com/coveo/platform-client/pull/385) which I am currently correcting.
I adjust the visibility of certain attributes in the interfaces of the Source part

fix(source): required attributes in SourceInformation

---

src/resources/Enums.ts
src/resources/MachineLearning/MachineLearningInterfaces.ts

feat(modelinformation): +extraConfig field to modelInformation interface

---

src/resources/Sources/SourcesDatasets/SourcesDatasets.ts
src/resources/Sources/SourcesDatasets/SourcesDatasetsInterfaces.ts
src/resources/Sources/SourcesDatasets/tests/SourcesDatasets.spec.ts

feat(source datasets): progress

---

src/resources/Enums.ts

Add new status `DELETING` for the source part but just pour the new attribute `extendedCurrentStatus`

fix(source): add new status DELETING for extendedCurrentStatus attribute

---

src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfiguration.ts
src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfigurationInterfaces.ts
src/resources/MachineLearning/CaseClassificationConfiguration/tests/CaseClassificationConfiguration.spec.ts
src/resources/MachineLearning/SmartSnippetsConfiguration/SmartSnippetsConfigurationInterfaces.ts

Reverts coveo/platform-client#404

Revert "feat(ml)!: added and updated Case Classification ML Config api calls"

---

README.md
src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfiguration.ts
src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfigurationInterfaces.ts
src/resources/MachineLearning/CaseClassificationConfiguration/tests/CaseClassificationConfiguration.spec.ts
src/resources/MachineLearning/SmartSnippetsConfiguration/SmartSnippetsConfigurationInterfaces.ts

feat(ml): added preview and content field api calls

---

src/resources/MachineLearning/ModelInformation/ModelInformationInterfaces.ts

Pretty straight forward. See title for as many details as I can give.

feat(ss): added smart snippets model info interface

---

src/resources/UsageAnalytics/Read/DataShare/DataShare.ts
src/resources/UsageAnalytics/Read/DataShare/DataShareInterfaces.ts
src/resources/UsageAnalytics/Read/DataShare/index.ts
src/resources/UsageAnalytics/Read/DataShare/tests/DataShare.spec.ts
src/resources/UsageAnalytics/Read/index.ts
src/resources/UsageAnalytics/UsageAnalytics.ts

feat(datashare): +API calls for data share feature

---

README.md
src/Endpoints.ts
src/tests/Endpoint.spec.ts

feat(env): add stg environment

---

src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts
src/resources/Search/test/Search.spec.ts

feat(search api): get field values list

---

src/resources/Enums.ts
src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

[SRC-4812](https://coveord.atlassian.net/jira/software/c/projects/SRC/boards/34?modal=detail&selectedIssue=SRC-4812) 
Added sort and filter queries to get all snapshots request
[SRC-4812]: https://coveord.atlassian.net/browse/SRC-4812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ResourceSnapshots): add parameters to get all snapshots

---

src/resources/PlatformResources.ts
src/resources/TableauService/ContentQuery/ContentQuery.ts
src/resources/TableauService/ContentQuery/ContentQueryInterfaces.ts
src/resources/TableauService/ContentQuery/index.ts
src/resources/TableauService/ContentQuery/tests/ContentQuery.spec.ts
src/resources/TableauService/TableauService.ts
src/resources/TableauService/index.ts
src/resources/TableauService/tests/TableauService.spec.ts
src/resources/index.ts

feat(tableauservice): +tableau service resource calls

---

src/resources/TableauService/ContentQuery/index.ts

fix(tableau-service): +export interfaces

---

src/resources/TableauService/index.ts

I forgot AGAIN to export the folder that contains the interfaces i need

fix(tableau service): did not export content query properly

---

src/resources/Enums.ts
src/resources/UsageAnalytics/Read/DataShare/DataShareInterfaces.ts

Status and error message were added to the data share interface for new entries in the admin-ui data share table

feat(datashare): +status,+errormessage to datashare

---

src/resources/License/LicenseInterfaces.ts

FOUND-4025
-   [ ] JSDoc annotates each property added in the exported interfaces -> no documentation yet on swagger
-   [ ] The proposed changes are covered by unit tests -> should I test this?
-   [ ] Commits containing breaking changes a properly identified as such -> None
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant) -> Nope

fix: add id to entitlement

---

src/resources/Limits/Limits.ts
src/resources/Limits/LimitsInterfaces.ts
src/resources/Limits/tests/Limits.spec.ts

feat(limits): added resource to fetch limits per limit type

---

src/resources/License/LicenseInterfaces.ts

feat(license): change entitlement model fields to match backend

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

-   [x] Commits containing breaking changes a properly identified as such: no breaking (mandatory goes optional)

feat(snapshot): add `deletionScope` option on `/apply`

---

src/resources/Sources/SourcesMetadata/SourcesMetadata.ts
src/resources/Sources/SourcesMetadata/SourcesMetadataInterfaces.ts
src/resources/Sources/SourcesMetadata/tests/SourcesMetadata.spec.ts
src/resources/Sources/index.ts

[CTINFRA-2810](https://coveord.atlassian.net/browse/CTINFRA-2810)
Add `getReportStatus` for a source metadata report. 

feat(metadata): add getReportStatus

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

TL:DR: Return type changed, see: https://coveord.atlassian.net/browse/SRC-4945.
This brings the change to the types.
-   [x] Commits containing breaking changes a properly identified as such: Will be merged with a `BREAKING CHANGE`, see below.
BREAKING CHANGE: `ResourceSnapshotsReportOperationResults` now is a record of 
```ts
{
resultCode: string;
message: string;
}
```
instead of a record of string.
The original string is now in the `message` property.
In short: 
```diff
- const myResult = myResults[0]
+ const myResult = …
```

feat(resource-snapshots)!: update resourceOperationResults type

---

src/resources/InsightPanelConfigs/InsightPanelConfigInterfaces.ts

- Added `qs` attribute in insight panel config interface under model associations.

feat(ip): added qs attribute to config pipeline interface

---

src/resources/Organizations/Organization.ts
src/resources/Organizations/tests/Organizations.spec.ts

The previous PR I opened for this branch did not interpolate the arguments in the query string so it effectively is ineffective at doing it's job.

[MLX-172] Feature/mlx 172 Modify expected endpoints

---

.github/workflows/cd.yml

There's no more comment or label for PRs. This should help diagnose why.

chore(release): debug semantic release

---

src/resources/Sources/SourcesMetadata/SourcesMetadataInterfaces.ts

[CTINFRA-2890]
Add a new field `isMapped` on the source metadata model. 
[CTINFRA-2890]: https://coveord.atlassian.net/browse/CTINFRA-2890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(metadata): add isMapped to Source Metadata interface

---

src/resources/Catalogs/ProductListingInterfaces.ts

Configuration node was missing from the model
🎩
-   [-] The proposed changes are covered by unit tests
-   [-] Commits containing breaking changes a properly identified as such
-   [-] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

feat(productlistings): add configuration node [COMSDZ-67]

---

src/resources/Enums.ts
src/resources/OrganizationAccess/Access.ts
src/resources/OrganizationAccess/AccessInterfaces.ts
src/resources/OrganizationAccess/tests/OrganizationAccess.spec.ts

Minor adjustment to the call, adding missing return value to the model and renamed accordingly to the changes

fix(access-tabs): return call missing and edit the jsdoc for clarity

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

Task: https://coveord.atlassian.net/browse/SRC-4937
This implementation is based on that documentation: https://platformdev.cloud.coveo.com/docs?urls.primaryName=Migration#/Snapshot/rest_organizations_paramId_snapshots_get
Improved interfaces for snapshot reports.

feat(snapshot): improvement of interfaces - SRC-4937

---

src/resources/Connectivity/ConnectivityInterface.ts
src/resources/Connectivity/CrawlingModules.ts
src/resources/Connectivity/index.ts
src/resources/Connectivity/tests/CrawlingModules.spec.ts

feat: crawling module log requests

---

src/resources/OrganizationAccess/AccessInterfaces.ts

Addressing small issue, this should not be an array of PrivilegeholderType since it's simply a string.

fix(accessinterface): privilegeholder type fix

---

src/resources/Catalogs/ProductListingConfiguration.ts
src/resources/Catalogs/ProductListingConfigurationInterfaces.ts
src/resources/Catalogs/ProductListingInterfaces.ts
src/resources/Catalogs/tests/ProductListingConfiguration.spec.ts
src/resources/PlatformResources.ts

[COMSDZ-99]( https://coveord.atlassian.net/browse/COMSDZ-99): Support product listing configuration routes

feat(product listing): support product listing configuration routes [COMSDZ-99]

---

src/resources/Catalogs/index.ts

Export product listing configuration functions and interfaces

COMSDZ-99: Export product listing configuration functions and interfaces

---

src/resources/Catalogs/index.ts
src/resources/Enums.ts

fix(product listing): change field operator type enum

---

src/resources/Enums.ts

fix(product listing): make fieldValueType enum lowercase

---

src/resources/Products/Product.ts
src/resources/Products/tests/Product.spec.ts

Support new parameter for products post call. 

[COMSDZ-102] add refreshCache to products api

---

.github/pull_request_template.md

docs(merge): add mention of conventional commits

---

src/resources/SearchUsageMetrics/LicenseMetrics/LicenseMetricsInterface.ts

another add-on of https://github.com/coveo/platform-client/pull/565, we've added the productId for more control over consumption dashboard stats display
**BONUS:** For the duration of the Centraide Campain 2022, author of unconventional commit on master will be strongly invited to amend by making a donation to Centraide …

feat(licenseMetric): +productId to license metric model interface

---

src/resources/Pipelines/ResultRankings/ResultRankings.ts
src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts

feat(pipelines result ranking): add support for bulk get result ranking API

---

src/resources/SchemaService/SchemaService.ts
src/resources/SchemaService/SchemaServiceInterfaces.ts
src/resources/SchemaService/test/SchemaService.spec.ts

[CTSVC-2321]
Added the endpoint to validate Slack tokens.
-   [ ] ~Commits containing breaking changes a properly identified as such~
-   [ ] ~[README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)~
[CTSVC-2321]: https://coveord.atlassian.net/browse/CTSVC-2321

feat(slack): add token validation endpoint

---

src/resources/Enums.ts

add expired value to ExportStatus

---

src/resources/InsightPanelInterfaces/InsightPanelInterface.model.ts

Change label prop of InsightPanelResultTemplateDetail to optional.

feat(Platform-Client): change result template label to optional

---

renovate.json

chore(renovate): valid json is better

---

.github/workflows/renovate-config-validator.yml
renovate.json

Visibly, I don't know how to write JSON anymore.
- Fixed the renovate.json (for real this time!)
- Added a linter on the config (because heck). Stolen from coveo/cli

chore(renovate): truly fix

---

src/resources/MachineLearning/Models/ModelsInterfaces.ts

All I did was add a property which is conditionally present  to the ModelInterfaces type definition

feat(mlinterfaces): add Property to MLInterfaces

---

src/resources/Pipelines/ResultRankings/ResultRankings.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts

feat(pipelines): add result ranking bulk delete

---

src/resources/Sources/SourcesMetadata/SourcesMetadata.ts
src/resources/Sources/SourcesMetadata/SourcesMetadataInterfaces.ts

Add query param for sorting and ordering for the getMetadatareport call
[DISCO-27]: https://coveord.atlassian.net/browse/DISCO-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

feat(metadata): add filter, sortBy and order to param

---

src/resources/HostedPages/HostedPages.model.ts
src/resources/HostedPages/HostedPages.ts
src/resources/HostedPages/index.ts
src/resources/HostedPages/tests/HostedPages.spec.ts
src/resources/PlatformResources.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

https://coveord.atlassian.net/browse/KIT-2243
https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20Interface%20Service#/Hosted%20Page/

add HostedPages

---

src/resources/HostedPages/HostedPages.model.ts
src/resources/HostedPages/HostedPages.ts
src/resources/HostedPages/index.ts
src/resources/HostedPages/tests/HostedPages.spec.ts
src/resources/PlatformResources.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

Redo of #616, but with a squash and merge.
This is an 'admin' history rewrite, I'll skip the reviews.

feat: add hostedPages

---

src/resources/UsageAnalytics/Read/Exports/Exports.ts
src/resources/UsageAnalytics/Read/Exports/ExportsInterfaces.ts
src/resources/UsageAnalytics/Read/Exports/tests/Exports.spec.ts

Add `exports/rowLimit` endpoint to the client to be used in the UI

feat(exportRowLimit): add call to rowLimit + test

---

src/resources/HostedPages/HostedPages.model.ts

fix: correct HostedPageCssFileInline typo

---

src/resources/Extensions/Extensions.ts
src/resources/Extensions/ExtensionsInterfaces.ts
src/resources/Extensions/tests/Extensions.spec.ts

* Added the `compileCode` call (see [Swagger](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Extension#/));
* Added the `ExtensionCompileCode`, `ExtensionCompileResult` and `ExtensionCompileError` interfaces. …

feat(extensions): add call to compile an extension's code

---

src/resources/CrawlingModule/CrawlingModuleInterfaces.ts

[CTINFRA-3207]
No my proudest moment at Coveo .... 
Je pense qu'il est temps que la semaine finisse
[CTINFRA-3207]: https://coveord.atlassian.net/browse/CTINFRA-3207?atlOrigin=eyJpIjoiNWR …

fix(crawling-module): typo in logRequestsEnabled for CrawlingModuleStatus interface

---

src/resources/IPXInterfaces/IPXInterface.model.ts

This PR add new fields to the IPXInterfaceConfiguration interface !
The added fields are: 
```
created
createdBy
updated
updatedBy
```

feat: new ipx fields

---

src/resources/HostedInterfacesCore/HostedInterfaceCoreConfig.model.ts
src/resources/IPXInterfaces/IPXInterface.model.ts
src/resources/IPXInterfaces/IPXInterface.ts
src/resources/IPXInterfaces/index.ts
src/resources/IPXInterfaces/tests/IPXInterface.spec.ts
src/resources/InsightPanelInterfaces/InsightPanelInterface.model.ts
src/resources/PlatformResources.ts

Adds IPX routes to the platform client now that the IPX is GA and not under a feature flag. Also updates the config object to reflect the last modifications.

feat(IPX): add IPX routes

---

src/resources/MachineLearning/MachineLearningInterfaces.ts

- Export AdvancedConfig interfaces (UrlReplacePatterns, QueryReplacePatterns, PageViewFiltered, CommerceSupport) for use in admin-ui
- Change the definition of commerceSupport interface

feat(mlx): Export advanced config interfaces from platform client

---

src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts
src/resources/Search/test/Search.spec.ts

feat(search): add call to list the fields

---

src/resources/BaseInterfaces.ts
src/resources/UsageAnalytics/Read/DataHealth/DataHealth.ts
src/resources/UsageAnalytics/Read/DataHealth/DataHealthInterfaces.ts
src/resources/UsageAnalytics/Read/DataHealth/index.ts
src/resources/UsageAnalytics/Read/DataHealth/tests/DataHealth.spec.ts
src/resources/UsageAnalytics/Read/index.ts

Add Data Health api definition to platform-client
[UA-8052]: https://coveord.atlassian.net/browse/UA-8052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

feat: UA-8052 Add Data Health API to platform client

---

src/resources/Enums.ts

For the bug [MLX-557](https://coveord.atlassian.net/browse/MLX-557)  I need to add a condition for PQS [here](https://github.com/coveo/admin-ui/blob/master/pages/model/src/components/data-preview/DataPreviewUtils.tsx#L73-L74) so I created this PR to add PQS in the ModelType enum.
-   [x] My merge commit message …

fix(MLX): add PredictiveQuerySuggest in the ModelTypes enum

---

src/resources/Activities/Activities.ts
src/resources/Activities/ActivitiesInterfaces.ts
src/resources/Activities/tests/Activities.spec.ts

feat: add api call and interface to get all the resources types and their corresponding operations

---

src/resources/Activities/Activities.ts

fix: return type J:ORG-226

---

src/resources/Projects/ProjectInterfaces.ts
src/resources/Projects/tests/Project.spec.ts

- Update interfaces to reflect the model present on the backend.

feat(workspace): update projects model

---

src/resources/UsageAnalytics/Read/DataHealth/DataHealthInterfaces.ts
src/resources/UsageAnalytics/Read/DataHealth/tests/DataHealth.spec.ts

Added missing query parameters for some Data Health API endpoints

feat(datahealthapi): adding missing query parameters to some endpoints

---

src/resources/Projects/ProjectInterfaces.ts
src/resources/Resources/ResourcesInterfaces.ts
src/resources/Resources/tests/Resources.spec.ts

fix(TSP-208): add missing properties on project resources

---

src/resources/MachineLearning/SmartSnippetsConfiguration/SmartSnippetsConfigurationInterfaces.ts
src/resources/MachineLearning/SmartSnippetsConfiguration/tests/SmartSnippetsConfiguration.spec.ts

Update SmartSnippets preview response, the old response is not deprecated, only added the new payload
https://platform.cloud.coveo.com/docs?urls.primaryName=Machine%20Learning%20Configuration#/Smart%20Snippets%20Configuration/rest_organizations_paramId_machinelearning_configuration_smartsnippets_preview_post
- …

feat(ml): Update SmartSnippets preview response

---

src/resources/BaseInterfaces.ts
src/resources/IPXInterfaces/IPXInterface.ts
src/resources/IPXInterfaces/tests/IPXInterface.spec.ts
src/resources/NextGenSearchPages/NextGenSearchPages.model.ts
src/resources/NextGenSearchPages/NextGenSearchPages.ts
src/resources/NextGenSearchPages/tests/NextGenSearchPages.spec.ts

[SVCINT-2734](https://coveord.atlassian.net/browse/SVCINT-2734)
Updated invalid types and routes in next gen search pages and ipx interface
[SVCINT-2734]: …

fix!: updated incorrect types and routes

---

src/resources/Organizations/Members/Members.ts
src/resources/Organizations/Members/tests/Members.spec.ts

This PR adds the Organization members resource from our api https://platformdev.cloud.coveo.com/docs?urls.primaryName=AuthorizationServer#/Organization%20Members (needed for a feature in the admin. One of the calls was used with backbone) …

feat(members): +members resource api + unit tests

---

src/resources/HostedInterfacesCore/HostedInterfaceVersionsCore.ts

chore: nitpik that were left behind by the automerge

---

src/resources/Projects/ProjectInterfaces.ts

-  TSP-214
- Remove deprecated project types

feat(TSP-214): remove deprecated project types

---

src/resources/Enums.ts
src/resources/Sources/SourcesInterfaces.ts
src/resources/Sources/SourcesSubInterfaces/Information.ts

CTCORE-9943 [PlatformClient] Update list filter interfaces and SourceModel
Added the new properties added to source service for displaying and sorting.

feat(sources): add new source properties and sorting options

---

src/resources/Catalogs/CatalogContent.ts
src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Catalogs/tests/CatalogContent.spec.ts

This was remove from main since it did not respect conventional commit 

feat: add new call to catalog content

---

.github/workflows/codeql.yml
.github/workflows/dependency-review.yml

it doesn't run on merge_group otherwise...

chore: switch to advanced codeql + merge_group everywhere :tm:

---

src/resources/ApiKeyTemplate/ApiKeyTemplate.ts

fix: modify to proper return type

---

src/resources/ApiKeys/ApiKeysInterfaces.ts
src/resources/Enums.ts

fix: add necessary attributes to api key model and fix issue with enum

---

src/resources/UsageAnalytics/Read/DataHealth/DataHealth.ts
src/resources/UsageAnalytics/Read/DataHealth/DataHealthInterfaces.ts
src/resources/UsageAnalytics/Read/DataHealth/tests/DataHealth.spec.ts

feat(UA-9399): added getEventsProblems call
Ref to the call: https://platformdev.cloud.coveo.com/docs/internal?urls.primaryName=Usage%20Analytics%20Read#/Data%20Health%20API%20-%20Version%2015/get__v15_datahealth_events_problems …

feat(UA-9399): added getEventsProblems call

---

src/resources/ApiKeys/ApiKeys.ts
src/resources/ApiKeys/ApiKeysInterfaces.ts
src/resources/ApiKeys/test/ApiKeys.spec.ts

https://coveord.atlassian.net/browse/ADUI-10318
This PR adds `duplicate` and `extend` api calls for API key

feat(apikeys): +duplicate, +extend api calls

---

src/resources/MachineLearning/ModelDetailedInfo/ModelDetailedInfoInterfaces.ts

** Release of the property is currently underway **

feat(modeldetailedinfo): add new property requiresAssociation

---

src/resources/MachineLearning/ModelListing/ModelListingInterfaces.ts

feat(modellisting): add new property requiresAssociation
- Added new property requiresAssociation
- Added deprecation warning for the older property (it had no  documentation) 

feat(modellisting): add new property requiresAssociation

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

Added enum values to support result rankings and statement groups for snapshots.

feat(SRC-5997): support result rankings and statement groups

---

src/resources/MachineLearning/ModelDetailedInfo/details/ModelDetails.ts
src/resources/MachineLearning/ModelDetailedInfo/details/ModelDetailsPreparationDetails.ts
src/resources/MachineLearning/ModelDetailedInfo/details/ModelDetailsTrainingDetails.ts

Sourced my changes from the API here's the PR where the properties were changed https://github.com/coveo-platform/ml-config-service/pull/2449
These properties are not documented, we're not documenting them. …

feat(modeldetails): adding properties for supporting case classification

---

src/resources/AnalyticsAdmin/Properties/PropertiesInterfaces.ts

Trying to update the platform-client version in the UI uncovered a issue, given this is such a small change I prefer to roll it back in the mean time as to not block the project. 

feat(UA-9902): rollback the null tracking id change

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

Added support for Catalogs in Resource Snapshots

feat(SRC-6089): added support for catalogs in snapshot

---

src/resources/ApiKeys/ApiKeys.ts
src/resources/ApiKeys/ApiKeysInterfaces.ts
src/resources/ApiKeys/test/ApiKeys.spec.ts
src/resources/Enums.ts

-   [x JSDoc annotates each property added in the exported interfaces

feat: add new filter by status param [ORG-1072]

---

package-lock.json
package.json
src/resources/Sources/SourcesInterfaces.ts

The source service now returns a `createdDate` on sources (https://github.com/coveo-platform/sourceservice/pull/2765), so let's add it to the interfaces.
Also fix a Windows incompatibility I found along the way.

feat(WEB-7489): add createdDate to source model

---

src/resources/MachineLearning/ModelDetailedInfo/ModelDetailedInfoInterfaces.ts

To be released in this PR https://github.com/coveo-platform/ml-config-service/pull/2514/files

feat(modeldetailedinfo): adding a new property called isLicensed

---

src/resources/ApiKeys/ApiKeysInterfaces.ts
src/resources/Enums.ts

feat: add privacy level to api key model

---

src/resources/MachineLearning/MachineLearningInterfaces.ts

Documentation taken from the other property which represents the exact same thing except the current status vs last status.
Backend PR : https://github.com/coveo-platform/ml-config-service/pull/2531 …

feat(machinelearninginterfaces): added the property lastBuildStatus

---

src/resources/ApiKeys/ApiKeysInterfaces.ts
src/resources/Enums.ts

fix: add composed object instead

---

src/resources/Organizations/Organization.ts
src/resources/Organizations/OrganizationInterfaces.ts
src/resources/Organizations/tests/Organizations.spec.ts

feat: added new parameter filter to listApiKeysPrivileges API

---

.github/pull_request_template.md
src/resources/SearchUsageMetrics/SearchHubs/SearchHubs.ts
src/resources/SearchUsageMetrics/SearchHubs/SearchHubsInterface.ts

https://coveord.atlassian.net/browse/ORG-1143

feat: removing minimumQueries from search hub list call

---

src/resources/Enums.ts

feat: add new enum value for the api key filter

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

https://coveord.atlassian.net/browse/TSP-703
Added string to be used in the following issue : https://coveord.atlassian.net/browse/SRC-6256
It is necessary for the following PR to be opened : https://github.com/coveo-platform/admin-ui/pull/14884
Here is the backend PR to show that the SETTING strings is correct : https://github.com/coveo-platform/migrationservice/pull/2038
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md …

chore(snapshot): add necessary string for query pipeline settings

---

src/resources/Projects/ProjectInterfaces.ts

- We are adding support for additional resources in projects (see resourceType [here](https://platform.cloud.coveo.com/docs?urls.primaryName=Workspace#/Resources/rest_organizations_paramId_resources_paramId_get))
- These resources are behind a feature flag and will be hidden by default
-   [ ] My merge commit …

feat(projects): support commerce resources in projects

---

CODEOWNERS

https://coveord.atlassian.net/browse/KIT-4542

chore(codeowners): replace @coveo/dx by @coveo/dxui
