.travis.yml
README.md
commitlint.config.js
package-lock.json
package.json

Configured the [semantic-release package](https://github.com/semantic-release/semantic-release).
- Travis CI will now automatically release in npm, create tags in github and generate changelogs based on the commit messages.
- The [conventional commit messages format](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) will be enforced by [commitlint](https://github.com/conventional-changelog/commitlint)
- To facilitate writing commit messages that follow the required format, I added [commitzen](https://github.com/commitizen/cz-cli)
- Commitzen is configured to hook onto the `git commit` command so if you were working with the command line, it changes nothing in your workflow other than the new CLI asking you questions.
- If you were using any GUI based tool to write you commit messages …

Configure semantic-release

---

README.md
src/APICore.ts
src/CoveoPlatform.ts
src/tests/APICore.spec.ts
src/tests/CoveoPlatform.spec.ts

Added the possibility to configure custom response handlers. I updated the [README](https://github.com/coveo/platform-client/blob/enable-custom-response-handlers/README.md#error-handling) to describe their usage.

feat: custom response handlers

---

src/APICore.ts
src/PlatformClient.ts
src/tests/APICore.spec.ts
src/tests/PlatformClient.spec.ts

`PlatformClient.initialize` method makes POST request to `/oauth/check_token` on the coveo platform in order to ensure the validity of the provided access token. The service behind that call only accepts a [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) object as request body. Currently the request body is sent as JSON string which results in `invalid token error` (I guess the server ends up checking a null token).

Fix PlatformClient.initialize method

---

package.json
src/Entry.ts
src/handlers/index.ts
src/resources/Catalogs/index.ts
src/resources/index.ts
tsconfig.build.json

When consuming the `platform-client` package, importing interfaces becomes a real pain.
Before the fix:
```ts
import {GroupModel} from '@coveord/platform-client/dist/definitions/resources/Groups/GroupsInterfaces';
```
After the fix:
```ts
import {GroupModel} from '@coveord/platform-client';
```

fix(typings): export all types from the package root

---

src/APICore.ts
src/resources/Groups/Groups.ts

Return types of the `create` and `update` methods of the group resource were wrong. Those methods don't return the `GroupModel`. 
- `create` actually returns `{id: string}`
- `update` actually returns no content.

fix(groups): create and update methods wrong return types

---

src/resources/ApiKeys/ApiKeysInterfaces.ts
src/resources/BaseInterfaces.ts
src/resources/MachineLearning/ModelInformation/ModelInformationInterfaces.ts
src/resources/Pipelines/MLAssociations/MLAssociationsInterfaces.ts

I've moved model info interfaces to Machine Learning resource, however, all the information are not documented in Swagger yet, some change may occur in the future. 
Also, I've replaced all the empty object type `{}` with `any`, because empty object could be limited in some occasion and does not have special meaning.

feat(modelinfo): update modelinfo interfaces

---

README.md
jest.setup.ts
package-lock.json
package.json
src/APICore.ts
src/Entry.ts
src/Errors.ts
src/PlatformClient.ts
src/tests/APICore.spec.ts
src/tests/PlatformClient.spec.ts

```ts
// Supposing we have a platform-client instance named "Platform"
Platform.abortPendingGetRequests();
```
Aborted promises won't resolve and won't reject, they will simply remain pending. However those requests will be identified as "cancelled" by the browser if you use the platform-client in such environment.

Add a way to abort pending get requests

---

src/resources/SecurityCache/SecurityCache.ts

Call type for list was not returning an array.

fix(securitycache): now return arrays when fetching lists

---

package.json
src/PlatformClient.ts
src/resources/BaseInterfaces.ts
src/resources/Enums.ts
src/resources/Fields/FieldsInterfaces.ts
src/resources/Groups/GroupsInterfaces.ts
src/resources/Groups/Realms/GroupRealmInterfaces.ts
src/resources/Groups/Realms/tests/GroupRealm.spec.ts
src/resources/SecurityCache/SecurityCacheInterfaces.ts

Enums were not outputted in the minified bundle. Thats because they were not imported anywhere and webpack was identifying them as dead code.
I moved all enums in a single file, imported that file somewhere and identified it as having side effects to accelerate compilation.

fix(types): output enums in the minified bundle

---

src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/PipelinesInterfaces.ts
src/resources/Pipelines/tests/Pipelines.spec.ts

This API endpoint is used for fetching available pipelines in ML model tester and content browser, not documented in swagger yet.

feat(pipeline): add pipeline resource for ml test

---

README.md
src/APICore.ts
src/ConfigurationInterfaces.ts
src/resources/index.ts
src/tests/APICore.spec.ts

This way we'll ensure the org is always the right one at the time of making the calls.

fix(platformclient): provide an organization id retriever function

---

package.json
src/PlatformClient.ts
webpack.config.js

My fix from yesterday wasn't working after all. Found out the real cause :crossed_fingers:. Our webpack config wasn't using our `Entry.ts` file as actual entry :open_mouth:

build(webpack): use the Entry.ts file as webpack entry

---

src/resources/Saml/Saml.ts
src/resources/Saml/tests/Saml.spec.ts

I did a typo when implementing the saml identity provider calls. The correct path is `identityprovider` and not `identityProvider` (see https://platformdev.cloud.coveo.com/docs/?api=AuthorizationServer#/Saml32Identity32Providers).

fix(saml): change "identityProvider" path for "identityprovider"

---

src/resources/Organizations/Organization.ts
src/resources/Organizations/OrganizationInterfaces.ts
src/resources/Organizations/tests/Organizations.spec.ts

I tried to use `Platform.organization.get` and noticed there were some missing fields in the response.
In the Swagger call, it mentions the `additionalFields` which was not fronted, so I added that as an option to the GET call.
I then adapted the response model to assume that those fields might be null.
I then added known values for `AdditionalFields`, it doesn't look like it actually works for auto-completion though 🤔
And then I added the `status` call, because, in fact, this is what I needed in the first place 😄

Add organization status call and options for GET organization

---

src/APICore.ts
src/ConfigurationInterfaces.ts
src/PlatformClient.ts
src/features/APIFeature.ts
src/features/APIWithHooks.ts
src/features/tests/APIWithHooks.spec.ts
src/resources/PlatformResources.ts
src/resources/Resource.ts
src/resources/tests/Resource.spec.ts
src/tests/PlatformClient.spec.ts

The goal here is to allow cherry-picking hooks before and after requests.
For instance, I would like to be able to support a couple of use cases:
* `client.withFeature(requestId(FETCH_ACTION)).get()` that would automatically dispatch the actions for "request started", "request failed" and "request succeeded".
* `client.withFeature(toastErrorNotification())` that would automatically prompt a toast on known errors.
I would also like to have to features either at large in a client (`client.withFeature(x).catalog`) or cherry-picked before executing a query: `client.catalog.withFeature(x)`.
So here is my early PoC. I would like to get some feedback on the feature, whether you like it, whether you see better/cleaner way of doing this.
The way I built it now, I really like that I didn't have to …

API Features for Client and Resources

---

src/Entry.ts
src/features/index.ts

I wanted to use `APIWithHooks` but it was not exposed 🤦‍♂

fix(apihooks): expose apiwithhooks

---

package.json
src/resources/Enums.ts

The commitizen cli was being prompted whenever we would commit something, even if we were already providing a valid commit message, which was quite a bit annoying. 
I removed the commitzen cli hook on the `git commit` command and added a npm script to prompt the commit helper cli when needed. The cli tool will now be used more as an opt-in feature rather than an obligation.
To commit changes, you will now have 2 options:
- run `npm run commit-cli`: the commitizen cli will be prompted and will ask you questions in order to generate a proper commit message.
- commit normally using your preferred method (you still need to write a commit message that follows the conventional commit pattern or it won't let you commit)

Remove commitizen hook on `git commit` command

---

.travis.yml

Travis was running builds for all branches (even if no PRs are opened on the branch).
With this change TravisCI will still trigger builds for PRs, but will not build other branches than master.

ci(travis): prevent builds on other branches than master

---

src/resources/MachineLearning/ModelConfiguration/ModelConfiguration.ts
src/resources/MachineLearning/ModelConfiguration/tests/ModelConfiguration.spec.ts

Currently, we have `headers: {'Content-Type': 'application/json'}` for PUT method by default, however, we will need the Content-Type to be 'text/plain' for the update request of advanced model configuration.

fix(modelconfiguration): update content-type

---

src/resources/MachineLearning/Models/Models.ts
src/resources/MachineLearning/Models/tests/Models.spec.ts

used the former get call for the simpler get and moved the get call to the more apropriate
getDetails
BREAKING CHANGE: the get call will not get the same response (it is not used in the admin yet
though)

refactor(ml-model): added get call renamed former get for getDetails

---

src/APICore.ts
src/PlatformClient.ts
src/features/APIWithHooks.ts
src/features/tests/APIWithHooks.spec.ts
src/resources/PlatformResources.ts
src/resources/Users/User.ts
src/resources/Users/UserInterfaces.ts
src/resources/Users/index.ts
src/resources/Users/tests/User.spec.ts
src/resources/tests/PlatformResources.spec.ts
src/tests/APICore.spec.ts
src/tests/PlatformClient.spec.ts

https://platformdev.cloud.coveo.com/docs/?api=AuthorizationServer#!/Users/rest_users_paramId_get
Added some logic to reuse the `UserModel` (current user) coming from the token information. We already fetch to check the token when initializing the platform client instance anyway.

Add the `user` resource

---

src/resources/Enums.ts

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
We need _en_ and _fr_ for now, but all the languages in the list of ISO 639-1 should be added at the end of the day (**not today**)

feat(enum): add en and fr to languagecode

---

src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/PipelinesInterfaces.ts
src/resources/Pipelines/tests/Pipelines.spec.ts

Added the following calls on the `pipeline` resource:
- `list`
- `get`
- `delete`
- `update`
- `duplicate`
- `create`
BREAKING CHANGE: `pipeline.listBasicInfo` has been replaced by `pipeline.list`
BREAKING CHANGE: `pipeline.getBackendVersion` renamed to `getMLVersion`

Add some calls to the pipeline resource

---

src/resources/SecurityCache/SecurityCacheInterfaces.ts

This changeset adds the onPremisesEnabled parameter to Security Providers, which reflects the platform's json. It would be used to differentiate on-premises security providers from cloud providers in the UI.
[CTINFRA-795]
[CTINFRA-795]: https://coveord.atlassian.net/browse/CTINFRA-795

feat(security): add on-premises enabled to interface

---

package-lock.json
package.json
src/APICore.ts
src/features/APIWithHooks.ts
src/features/tests/APIWithHooks.spec.ts
src/handlers/ResponseHandlers.ts
src/handlers/tests/ResponseHandlers.spec.ts
src/resources/Pipelines/Statements/Statements.ts
src/resources/Pipelines/Statements/tests/Statements.spec.ts
src/tests/APICore.spec.ts

Added the `api.getFile` method on the api core that handles the response by returning a blob instead of parsing the response into a JSON object. 
When fetching a file, we don't want to parse the response into a JSON object because it is not necessarily a json file (in the case of the exportCSV, it is a `.csv` file obviously).

fix(pipeline-statements): make exportCSV resolve with a blob

---

src/resources/Pipelines/Statements/StatementsInterfaces.ts

Some features (such as the query parameters overrides) will have additional fields not listed in the generic StatementModel interface.

fix(statements): allow additional statement fields

---

src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts

Require the new `availability.idField` in new catalogs.
So it is still optional when you _get_ one, and you can still _save_ one if the original doesn't have it set yet.
At some point, when all catalogs are migrated in prod, we will flip the switch to make it mandatory everywhere and we will be able to remove both `Create` models!

feat(catalog): require availability.idField

---

src/resources/Catalogs/CatalogInterfaces.ts

[COM-396]: https://coveord.atlassian.net/browse/COM-396
This is to reflect the current state of our service. We will be migrating everyone to `sourceIds`, eventually.
So you can have `{ sourceIds: []}`, `{ sourceIds: [], query: '' }` or the legacy `{ query: '' }`

feat(catalog): add source scope to catalog

---

src/resources/BaseInterfaces.ts
src/resources/Sources/Sources.ts

I tried using `Platform.source.list()` and shit went wrong because the actual returned data is not contained in `items`, but in `sourceModels`.
Let me know if you'd rather just have a different `PageModel` implementation instead of the generic one here (I was on the fence between those two ideas)

fix(sources): fix wrong pagemodel for sources

---

src/APICore.ts
src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts
src/tests/APICore.spec.ts

This allows a request without bearer token

feat(getsnapshotcontent): use fetch directly in resource snapshot method

---

src/resources/Enums.ts
src/resources/UsageAnalytics/Read/Dimensions/Dimensions.ts
src/resources/UsageAnalytics/Read/Dimensions/DimensionsInterfaces.ts
src/resources/UsageAnalytics/Read/Dimensions/index.ts
src/resources/UsageAnalytics/Read/Dimensions/tests/Dimensions.spec.ts
src/resources/UsageAnalytics/UsageAnalytics.ts
src/resources/UsageAnalytics/index.ts

In order to fetch option values for `Language`, `Origin 1` and `Origin 2` in Model Testing additional parameters, we'd need the same call that the UA UI is doing to provide auto complete in the Visit Browser.

feat(ua): add dimensions resource for model testing additional parameters

---

src/resources/MachineLearning/DNEConfiguration/DNEConfiguration.ts
src/resources/MachineLearning/DNEConfiguration/DNEConfigurationInterfaces.ts
src/resources/MachineLearning/DNEConfiguration/index.ts
src/resources/MachineLearning/DNEConfiguration/tests/DNEConfiguration.spec.ts
src/resources/MachineLearning/MachineLearning.ts
src/resources/MachineLearning/index.ts

https://platformdev.cloud.coveo.com/docs/?api=MLConfig#/Dynamic32Navigation32Experience32Configuration
Side note:
We could abstract the call to `/documentextractionquery` inside the create model call in the platform-client. That way it would remove this complexity from the admin UI repo.

feat(ml): add dne configuration resource

---

src/resources/Organizations/OrganizationInterfaces.ts

new field added to list organization call : type. That filter on org type. Added so the test org will be filtered out with Developer type

feat(organizationinterface.ts): +type?:string in ListOrganizationOptions

---

src/resources/Enums.ts
src/resources/Sources/Sources.ts
src/resources/Sources/SourcesInterfaces.ts
src/resources/Sources/tests/Sources.spec.ts

The Sources interfaces in swagger are a bit different from what we have in actual calls. This PR was created to update typing for `SourceModel` and `CreateSourceModel` according to the backbone model we currently use. Once Source team update swagger, I'll create another PR for the final adjustment. 
One thing to note, `SourceModel` here is a base model shared by all source types, and each type of source can have its proper additional properties.

feat(sources): update interfaces with current model in backbone

---

src/resources/CaseAssistConfigs/CaseAssistConfigInterfaces.ts
src/resources/CaseAssistConfigs/tests/CaseAssistConfig.spec.ts

The model was updated in the customer service api to remove `fieldsToFeed`.
It is removed here to remain consistent with the service.
> This change is breaking as the current model is in use in packages/jsadmin-service in admin-ui

fix(update)!: case assist config model

---

src/resources/SchemaService/SchemaServiceInterfaces.ts

I added a third field in the SchemaEntity object for the real logical name of the entity to prevent situations where the display name is the same for some entities.
{
"name": "sys_amb_message0001",
"id": "ae5b6d142c1700100c1dbc48b5c9f585",
"displayName": "AMB Message"
},
{
"name": "sys_amb_message0002",
"id": "b65b6d142c1700100c1dbc48b5c9f59d",
"displayName": "AMB Message"
},
{
"name": "sys_amb_message0004",
"id": "b65b6d142c1700100c1dbc48b5c9f5cc",
"displayName": "AMB Message"
},

feat: add displayName to entities interface

---

src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts

[COM-567]
We removed `variant.fields` and `availability.fields` properties when creating and updating a catalog, but still return them when fetching the catalog.
Also, we now return `product.fields`.
So this update reflects those two changes :)
[COM-567]: https://coveord.atlassian.net/browse/COM-567

feat(catalog): remove fields from catalog creation

---

tsconfig.json

BREAKING CHANGE: Need to change tsconfig module to commonjs from esnext to compile Entry.js. ES syntax causing build to fail during qpl-converter tests

fix(tsconfig.json): changing from esnext to commonjs for qpl-converter

---

src/Endpoints.ts
src/tests/Endpoint.spec.ts

Adding Australia to the list of supported regions. This region will technically only be available in prod, but it doesn't prevent the platform-client from supporting it in the other envs.

feat(endpoints): add australia region

---

src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts

[COM-588](https://coveord.atlassian.net/browse/COM-588)
This PR adds a new route and a new `Cached` interface to allow usage of the catalog fields endpoint.

feat(catalog): create route and interface to use catalog fields

---

src/resources/Pipelines/PipelinesInterfaces.ts

This one is not documented in swagger yet, but here is an example:

feat(pipelines): update interface

---

src/resources/Catalogs/CatalogConfiguration.ts
src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Catalogs/index.ts
src/resources/Catalogs/tests/Catalog.spec.ts
src/resources/Catalogs/tests/CatalogConfigurations.spec.ts
src/resources/PlatformResources.ts
src/resources/tests/PlatformResources.spec.ts

[COM-702]
This matches many updates from the Catalog API. Changes include:
* `scope` is deprecated in favor of two first-class properties, `sourceId` and `availabilitySourceId`.
* You can create a catalog with a `catalogConfigurationId`, which is a second object in the Catalog Service. Sending the "old" structure will create a configuration for you.
* `product` + `variant` + `availability` are now set in the Catalog Configuration, so the first-class properties are now deprecated.
* Added the `catalogconfigurations` API which is pretty straightforward
It was tested with a link to `admin-ui`, so no breaking change here
[COM-702]: https://coveord.atlassian.net/browse/COM-702

feat(catalog): update interface with catalog configuration

---

package-lock.json
package.json
src/resources/Enums.ts
src/resources/Extensions/Extensions.ts
src/resources/Extensions/ExtensionsInterfaces.ts
src/resources/Extensions/tests/Extensions.spec.ts

Added support for the following extension operations:
- create
- update
- delete
- enable
- disable
- get
The interface was built from this [doc](https://docs.coveo.com/en/7/cloud-v2-api-reference/extension-api#operation/). However, the documented response from the create operation didn't match the actual value. I decided to use the full `ExtensionModel` interface as the response instead of just the ID.
This doesn't cover the extension testing and version APIs. These may be covered in a later PR.

feat(extension): added support for extension CRUD operations

---

src/resources/License/License.ts
src/resources/License/tests/License.spec.ts

in swagger theres an endpoint to update the whole license, but theres no call to this endpoint in
platform-client. This endpoint is needed for the next part to [this PR](https://coveord.atlassian.net/browse/ADUI-6297)
[Swagger endpoint in question](https://platformdev.cloud.coveo.com/docs/internal/?urls.primaryName=Platform#/License/rest_organizations_paramId_license_put)

feat(license): added a call to update the whole license

---

src/resources/ResourceSnapshots/index.ts
src/resources/ResourceSnapshots/links/Links.ts
src/resources/ResourceSnapshots/links/tests/Links.spec.ts

add delete all links to clear all the links in a organization to be able to restart synchronization from scratch

feat(resource snapshots): add deleteAllLinks

---

src/resources/Connectivity/Connectivity.ts
src/resources/Connectivity/ConnectivityInterface.ts
src/resources/Connectivity/index.ts
src/resources/Connectivity/tests/Connectivity.spec.ts
src/resources/PlatformResources.ts
src/resources/index.ts
src/resources/tests/PlatformResources.spec.ts

Add new API call to the Connectivity service. Those will be used to generate downloadable logs for a source.

feat(connectivity service): add basic call to the diagnostic api

---

src/resources/Catalogs/CatalogConfiguration.ts
src/resources/Catalogs/tests/CatalogConfigurations.spec.ts

While working on COM-708, more specifically the deletion of a configuration, I noticed these parameters were misnamed. I also adjusted the tests.
[COM-708]
[COM-708]: https://coveord.atlassian.net/browse/COM-708

feat(catalog): correct configurations parameter names

---

package-lock.json
package.json
src/APICore.ts
src/resources/Pipelines/Statements/Statements.ts
src/resources/Pipelines/Statements/tests/Statements.spec.ts
src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts
src/tests/APICore.spec.ts
src/utils/FormData.ts

FormData is a Web JS only API, not available in NodeJS.
This PR adds a way to load https://github.com/form-data/form-data when it's not available.
If you guys prefer, we can also just document how to polyfill it from an end user point of view, but I personally find this to be very annoying for end users.
Just tell me what you prefer, either like this PR propose, or a README change with the documentation on how to do it as a end user.
Also replaced all `formData.set` to `formData.append`, as it is not present on the most popular node module for FormData. 
Everywhere I could see in the codebase, using append instead of set should not produce any difference in the end.
https://coveord.atlassian.net/browse/CDX-63

fix(api): support node js environments with FormData

---

src/ConfigurationInterfaces.ts

For some operations, no organization ID is actually required by the platform.
For example, if you need to `list all org` ( https://platformdev.cloud.coveo.com/docs?urls.primaryName=Organization#/Organizations/rest_organizations_get), `list regions` ( https://platformdev.cloud.coveo.com/docs?urls.primaryName=Organization#/Region%20Configuration/rest_global_regions_get ) etc.
While in theory you could, as a consumer of the library, pass in `organizationId: ''` when creating a PlatformClient, I propose adding an explicit parameter, globally exported.
Just so the consumer code can do something like: 
```
import PlatformClient, {
NoOrgIDRequiredForGlobalOperations,
} from '@coveord/platform-client';
const client = new PlatformClient({
accessToken: myToken,
environment: myEnvironment, …
```

feat(config): support explicit no orgID for configuration

---

src/resources/Catalogs/CatalogInterfaces.ts

New `Edit Catalog` page will not be saving a product (objecttype/field) in the catalog model as it is moved to `Edit Configuration`.

feat(catalog): product hierarchy is optional

---

src/resources/SchemaService/SchemaService.ts
src/resources/SchemaService/SchemaServiceInterfaces.ts
src/resources/SchemaService/test/SchemaService.spec.ts

Updates to the Schema Service Interfaces to reflect changes to the Schema Service API (starting [here](https://github.com/coveo/schema-service/pull/434) and continuing through multiple PRs).
This PR contains the following changes : 
- support for 3 new routes: 
- `/translate/specific` to translate a Generic Objects to Get to a source-specific one
- `/translate/generic` to translate a source-specific Objects to Get to a generic one
- `/translate/specificWithFields` to translate a Generic Objects to Get to a source-specific one with the Generic Objects to Get fields settings
- update `SchemaEntity`, `SchemaFields`, `SchemaField`, `SchemaServiceQueryParams` and `ObjectsToGetObject` interfaces to reflect changes to the API responses
SNOW-544

feat(schema update): update schemaservice interface

---

src/resources/CaseAssistConfigs/CaseAssistConfig.ts
src/resources/CaseAssistConfigs/CaseAssistConfigInterfaces.ts
src/resources/CaseAssistConfigs/CaseAssistPreviewInterfaces.ts
src/resources/CaseAssistConfigs/tests/CaseAssistConfig.spec.ts

This PR exposes the [/classify](https://platform.cloud.coveo.com/docs?urls.primaryName=Customer%20Service#/Suggestions/postClassify) and [documents/suggest](https://platform.cloud.coveo.com/docs?urls.primaryName=Customer%20Service#/Suggestions/getSuggestDocument) Case Assist API calls.
These calls are very similar to the preview ones, except they return suggestions for an existing Case Assist configuration.

feat(sfint-3612): Expose "classify" and "documents/suggest" API calls to retrieve suggestions.

---

src/resources/SecurityCache/SecurityCache.ts
src/resources/SecurityCache/tests/SecurityCache.spec.ts

I've added the new sec cache call [here](https://platformdev.cloud.coveo.com/docs/internal?urls.primaryName=SecurityCache#/Security%20Cache/rest_organizations_paramId_securitycache_entities_paramId_entity_post)

feat: added new call for provider entity

---

src/resources/License/License.ts
src/resources/License/tests/License.spec.ts

The client currently only expose retrieving a section of the license.
There's information that's only available globally, not part of a specific section (eg: the type of the license -- TRIAL, PRODUCTION etc.)
Also, the current `get` function for the License resource is wrong, since it does not actually return a `LicenseModel`, but only an arbitrary section of the full license.
I did not want to touch this as part of this PR though, as it would be a breaking change, and yeah ... 🤷 
https://coveord.atlassian.net/browse/CDX-68

feat(license): support full license API call

---

src/resources/SchemaService/SchemaService.ts
src/resources/SchemaService/SchemaServiceInterfaces.ts

Added the `SimpleSchemaEntity` interface to differentiate an incomplete and a complete Entity
Switch param `entityName` for `entityId` in `getFields`
SNOW-554

fix(schema update)!: streamline schema interface

---

.releaserc.json

I merged this PR https://github.com/coveo/platform-client/pull/252, the build was green but the release was failed. It seems that `BREAKING CHANGES` should be `BREAKING CHANGE` in the commit message.
I tried to add `noteKeywords` to include `BREAKING CHANGES` by creating the file `.releaserc.json`.
https://github.com/semantic-release/commit-analyzer#usage
https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#configuration-file
Also included default plugins `['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/npm', '@semantic-release/github']` to be safer. 
https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#plugins
Unfortunately, I'm not able to test this …

build(release): add noteKeywords parser options

---

src/resources/Connectivity/Connectivity.ts
src/resources/Connectivity/ConnectivityInterface.ts

BREAKING CHANGE: return logRequestId and not logRequest - not my proudest moment
That's what the call return

A quick one - feat(connectivity): change return type for requestLog

---

src/resources/Pipelines/ResultRankings/ResultRankings.ts
src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts

Update resultRankings.list parameters to allow filtering by statement groups. Update
resultRanking.list response to type groupedBy informations.
https://coveord.atlassian.net/browse/SEARCHAPI-5679

feat(result-rankings): update resultRankings.list params/response types

---

src/resources/SchemaService/SchemaService.ts
src/resources/SchemaService/test/SchemaService.spec.ts

Add `/defaultObjectsToGet` route in `SchemaService` interface. It retrieves the default Objects to Get configuration for a given source type
THIS PR is needed for [THIS PR in admin-ui](https://github.com/coveo/admin-ui/pull/1935)

Feat snow 547 references otg interface

---

src/resources/MachineLearning/Models/Models.ts
src/resources/MachineLearning/Models/tests/Models.spec.ts

New method uses same registration model interface that is documented under the [Platform API Swagger docs](https://platform.cloud.coveo.com/docs?urls.primaryName=Machine%20Learning#/Machine%20Learning%20Models/rest_organizations_paramId_machinelearning_models_paramId_put)

feat(models): new method in Models class for updating Models

---

src/resources/Pipelines/MLAssociations/MLAssociations.ts
src/resources/Pipelines/MLAssociations/tests/MLAssociations.spec.ts

The current ML associations URL for dissociating a model from a query pipeline includes the modelId
which is not included according to the Swagger docs. This has been confirmed a breaking issue by
using the platform-client.
BREAKING CHANGE: Method signature change for MLAssociations.dissociate

fix(mlassociations.ts): model Dissociate URL updated to follow docs

---

src/resources/Pipelines/Statements/Statements.ts
src/resources/Pipelines/Statements/tests/Statements.spec.ts

Strings can now be passed to the importCSV method on Statements. FormData supports the use of File
and string references, however the Coveo API requires a file name be set. This change provides a
file name in the case of string arguments.
**Background**: This resolves an issue I came across where not including the file name in the `multipart/form-data` request would cause the Coveo API to error with a 400. The client can immediately cover this case by providing a file name for CSV imports.

feat(statements.ts): support for raw string form data in importCSV

---

src/resources/Pipelines/Statements/Statements.ts
src/resources/Pipelines/Statements/tests/Statements.spec.ts

I removed the legacy URL from a call in the search API as requested by David Reisch

fix(query pipelines): remove legacy url

---

src/resources/SecurityCache/SecurityCacheInterfaces.ts

The SecurityProviderModel interface has been updated to match the OpenAPI definition.
The expected interface can be seen in the Coveo docs [here](https://docs.coveo.com/en/14/cloud-v2-api-reference/security-cache-api#operation/createOrUpdateSecurityProviderUsingPUT_2).
BREAKING CHANGE: Updated the cascadingSecurityProviders property on SecurityProviderModel

fix(securityprovider): corrected cascading security provider interface

---

src/resources/PlatformResources.ts
src/resources/PushApi/PushApi.ts
src/resources/PushApi/PushApiInterfaces.ts
src/resources/PushApi/index.ts
src/resources/PushApi/tests/PushApi.spec.ts

Added the push API resource based on [Coveo docs](https://docs.coveo.com/en/12/cloud-v2-api-reference/push-api). This only includes Security Identity support for now.

feat(pushapi): added Security Identity management to push API resource

---

README.md
src/APICore.ts
src/ConfigurationInterfaces.ts
src/tests/APICore.spec.ts

PlatformClientOptions includes new optional property for fetch request configuration (RequestInit)
to allow various features such as global headers and HTTP(S) proxy agents

feat(apicore): configurable fetch requests in APICore

---

src/resources/SearchPages/SearchPages.ts
src/resources/SearchPages/SearchPagesInterfaces.ts
src/resources/SearchPages/tests/SearchPages.spec.ts

New methods include support for the headers endpoints:
- Get search page header
- Reorder resources in search page header
- Create CSS resource in a search page header
- Update CSS resource in search page header
- Delete CSS resource in search page header
- Append JavaScript resource to search page header
- Update JavaScript resource in search page header
- Delete JavaScript resource in search page header
See [Swagger documentation](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20Pages#/Search%20pages) for more info

feat(searchpages): support for headers (css/js) operations

---

src/resources/Catalogs/CatalogConfiguration.ts
src/resources/Catalogs/CatalogInterfaces.ts

https://coveord.atlassian.net/browse/COM-885
CatalogConfiguration::list takes a parameter CatalogsListOptions which itself contains a filter property. Changed list's parameter because we cannot filter configurations when we list them.

feat(catalog): fixed catalog configurations list parameter

---

src/resources/SchemaService/SchemaService.ts
src/resources/SchemaService/SchemaServiceInterfaces.ts
src/resources/SchemaService/test/SchemaService.spec.ts

Add the `getEntity` method to the SchemaService class.
This method is mainly used to resolve the `recordCount` of a given entity when given a `filter`.
Unit tests were updated.
Manually tested as part of the WORK-108 PR in admin-ui

WORK-108 add record count to schema interface

---

src/resources/Organizations/Organization.ts
src/resources/Organizations/tests/Organizations.spec.ts

The list organization call return different types depending on if a `ListOrganizationOptions` is passed in or not as an argument.
When no `ListOrganizationOptions`, it does not return a `PageModel<OrganizationModel>`, it returns an `OrganizationModel[]` directly.
And since `ListOrganizationOptions` is optional, the final returned type was invalid.
I suspect this might be present for other API calls in the project... 🤔 
I did not do an exhaustive check of everything, though.

fix(organizations): fix return type for list organizations

---

src/resources/Organizations/Organization.ts

When using `organization.list(someParams)` the return type was `Promise<OrganizationModel[]>` instead of `Promise<PageModel<OrganizationModel>>`.
```ts
const params: ListOrganizationOptions = {perPage: 0};
this.list(); // Promise<OrganizationModel[]>
this.list(null); // Promise<OrganizationModel[]>
this.list(undefined); // Promise<OrganizationModel[]>
this.list({}); // Promise<OrganizationModel[]>
this.list({perPage: 0}); // Promise<PageModel<OrganizationModel>>
this.list(params); // Promise<OrganizationModel[]>  ⬅️ Wrong
```
```ts
const params: ListOrganizationOptions = {perPage: 0};
this.list(); // Promise<OrganizationModel[]>
this.list(null); // Promise<OrganizationModel[]>
this.list(undefined); // Promise<OrganizationModel[]>
this.list({}); // Promise<OrganizationModel[]> …
```

fix(organizations): list return type was wrong when using options

---

src/resources/MachineLearning/DNEConfiguration/DNEConfiguration.ts
src/resources/MachineLearning/DNEConfiguration/tests/DNEConfiguration.spec.ts

Added a new method to parse a document extraction query of the DNE configuration to a the Document extraction query model (in which it would return an object with an array of fields and an array of sources based on the query received).

feat(dne-configuration): add parseDocumentExtractionQuery method

---

src/resources/UsageAnalytics/Read/Exports/Exports.ts

There was an error in swagger. The ua call to delete a schedule should return void, not an ExportModel

fix(exports.ts): changed the return from ExportModel to void

---

src/resources/MachineLearning/DNEConfiguration/DNEConfiguration.ts

Decode query to make sure the latter is formatted correctly. Otherwise, the API call will never work.

Feat ADUI 6832 add a method to parse the document extraction query used for the dne configurations

---

src/resources/MachineLearning/DNEConfiguration/DNEConfiguration.ts
src/resources/MachineLearning/DNEConfiguration/tests/DNEConfiguration.spec.ts

I didn't includes the right URL (see [here ](https://platformdev.cloud.coveo.com/docs/?urls.primaryName=Machine%20Learning%20Configuration#/Dynamic%20Navigation%20Experience%20Configuration/rest_organizations_paramId_machinelearning_configuration_dne_documentextractionquerymodel_get)to confirm I did now include the expected route) for this method. Here's the correction

Feat ad UI 6832 add a method to parse the document extraction query used for the dne configurations

---

src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts

Add the `bypassCache` parameter which already exists on the catlalog api's `/fields` route.
[COM-681]
[COM-681]: https://coveord.atlassian.net/browse/COM-681

Allow bypassing catalog fields cache [COM-681]

---

src/resources/BaseInterfaces.ts
src/resources/GlobalGroups/GlobalGroupInterfaces.ts

- Global privileges don't have that `global` property. 
- `targetId` is optional

fix(privileges): fixing the types for privileges

---

src/resources/UsageAnalytics/Read/Snowflake/Snowflake.ts

The POST call to create user returns an object `SnowflakeUserModel` instead of `void`.

fix(snowflake): update create user response body

---

src/resources/MachineLearning/MachineLearningInterfaces.ts

the modelId parameter has been included in MLModelCreated and Swagger documentation fulfilled in the
interface where available
fix #259

fix(machine-learning): include modelId parameter in MLModelCreated

---

src/resources/index.ts

added the modifier to the resource index
FOUND-3517
I'm having import issues when running tests and it was suggested that it might be because the ModifierTemplate files are only exported at the /resources/ModifierTemplates level but not the upper /resources/index.ts level.
```
@coveord/jsadmin-v2: ERROR in ./src/settings-react/license/details/tests/DetailsComponent.spec.tsx
@coveord/jsadmin-v2: Module not found: Error: Can't resolve …
```

fix(modifiertemplates): added the modifier to the resource index

---

src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfigurationInterfaces.ts
src/resources/MachineLearning/CaseClassificationConfiguration/tests/CaseClassificationConfiguration.spec.ts

A breaking change was made in the dev api. See [here](https://github.com/coveo/ml-config-service/pull/576).
Break there means break here. monkey see monkey do, monkey pee all over you.

fix(machine-learning)!: change param key

---

src/resources/Fields/FieldsInterfaces.ts
src/resources/Fields/tests/Fields.spec.ts

A parameter was missing for the ListFieldsParams interface, used for the GET call that fetch all the fields. It is now possible to set the `facetsOnly` parameter, that indicates if we want to received only the fields that can be converted as facets.
https://platformdev.cloud.coveo.com/docs/?urls.primaryName=Field#/Fields/rest_organizations_paramId_indexes_page_fields_get

feat(fields-interfaces): add the facetsOnly parameter to the list call

---

src/resources/Sources/SourcesInterfaces.ts

The `forceLogin` property is used in the **Automatic form authentication** of the edit source page. I can't find any information in Swagger or in the backbone model to add JSDoc annotation at this moment.

feat(sources): add a new field to form auth interface

---

src/resources/Catalogs/CatalogInterfaces.ts

adding sourceId availabilitySourceId to catalog configuration associated models [COM-1052]
COM-1052
[COM-1052]: https://coveord.atlassian.net/browse/COM-1052

fix(catalog): adding sourceId availabilitySourceId to associated catalog

---

src/resources/License/License.ts
src/resources/License/LicenseInterfaces.ts
src/resources/License/tests/License.spec.ts

added call to list possible source types
FOUND-3547
Juste pour être sûr, si j'ai bien compris:
* Les licenses sont déjà une ressource qui existe et on export * dans le index.ts faique pas besoin de faire de quoi de spécial pour un nouveau call/model
* ${API.orgPlaceholder} est magique et j'ai pas besoin de passer l'orgId en param

feat(licenseapi): added call to list possible source types

---

src/resources/Enums.ts
src/resources/SearchInterfaces/SearchInterfaces.model.ts
src/resources/SearchInterfaces/tests/SearchInterfaces.spec.ts

Story: https://coveord.atlassian.net/browse/ADUI-7033
Update the interfaces to includes now a `ISortCriteria` interface, a `SortingBy `enum and update the `ISearchInterfaceConfiguration` interface to include the `ISortCriteria[]` parameter. 
This change should be included in this [story](https://coveord.atlassian.net/browse/SPAAS-698) before merging.

feat(search-interfaces): add sortCriteria interface

---

src/resources/Enums.ts
src/resources/Organizations/Members/Members.ts
src/resources/Organizations/Members/MembersInterface.ts
src/resources/Organizations/Members/index.ts
src/resources/Organizations/Members/tests/Members.spec.ts
src/resources/Organizations/Organization.ts
src/resources/Organizations/index.ts
src/resources/Organizations/tests/Organizations.spec.ts
src/resources/SearchUsageMetrics/LicenseMetrics/LicenseMetricsInterface.ts
src/resources/SearchUsageMetrics/tests/SearchUsageMetrics.spec.ts

Blocking a feature, this refactor (which is overdue anyway) will help us having a simpler and more
unified api
*** I've added JSDoc on previous pr that I forgot to add :shame: and change a param to an optional one 
https://github.com/coveo/platform-client/pull/318

refactor(organizationmembers): +getall +delete member api calls

---

src/resources/Organizations/Members/Members.ts

there was an error on the implementation

fix(members.ts): getAll returns an array, not a single object

---

src/resources/Pipelines/StatementGroups/StatementGroupsInterfaces.ts
src/resources/Pipelines/StatementGroups/tests/StatementGroups.spec.ts

Add a new `filter` param that allow to filter statement groups by searching for: group name,
condition content or user notes.
https://coveord.atlassian.net/browse/SEARCHAPI-5828

feat(statement-groups): add `filter` param to listing endpoint

---

src/resources/UsageAnalytics/Read/Filters/Filters.ts
src/resources/UsageAnalytics/Read/Filters/FiltersInterfaces.ts
src/resources/UsageAnalytics/Read/Filters/tests/Filters.spec.ts

functionality for the Filters API including permissions filters as well as healthcheck and status
calls
edit: also includes a fix commit for the return type of `getReportFilter`

feat(filters): support for permission filters

---

src/resources/UsageAnalytics/Read/Filters/Filters.ts

return types for getPermissionFilterTargets and updatePermissionFilterTargets updated to reflect Swagger docs. getPermissionFilterTargets returns FilterTargetsResponse and updatePermissionFilterTargets returns only a status code without a body.
BREAKING CHANGE: incompatible type changes

fix(filters): update return types on permission filter target endpoints

---

src/resources/SearchInterfaces/SearchInterfaces.model.ts
src/resources/SearchInterfaces/SearchInterfaces.ts
src/resources/SearchInterfaces/tests/SearchInterfaces.spec.ts

This story is to add the PUT call to update a search interface's accesses. I've also updated the content of the `IAccesses` model.

feat(search-interfaces): add updateAccesses

---

src/resources/Catalogs/CatalogConfiguration.ts
src/resources/Pipelines/ResultRankings/ResultRankings.ts
src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts

Add the new `copyTo` method to allow copying a list of result rankings rules to another pipeline
https://coveord.atlassian.net/browse/SEARCHAPI-5970

feat(result-rankings): add copyTo method

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

According to the API, a property of an export model must adhere to the following condition:
- Its key must be part of the `ResourceType` enum
- Its value must either be `null` or an array of strings.
-   [x] JSDoc annotates each property added in the exported interfaces.
- No additions.
-   [x] The proposed changes are covered by unit tests.
- No logic changes.
- IMHO, this is not a breaking change because even if you didn't adhere to the typing restrictions introduced here, the API would have denied the request. Therefore, I think it's a fix.
- Irrelevant.

fix(migration-export-model): strongly type snapshot export model

---

src/resources/Organizations/Organization.ts
src/resources/Organizations/tests/Organizations.spec.ts

Added a resource to change the support activated flag of an organization.

feat(organization.ts): added support status change for an organization

---

src/resources/Enums.ts
src/resources/Pipelines/StatementGroups/StatementGroups.ts
src/resources/Pipelines/StatementGroups/StatementGroupsInterfaces.ts
src/resources/Pipelines/StatementGroups/tests/StatementGroups.spec.ts

Update the statement group model to include the status of the group. Change the update() signature
to use the updateGroupModel. Add status + types filters to the list groups endpoint
BREAKING CHANGE: groups.update() now takes a UpdateStatementGroupModel instead of a
StatementGroupModel
https://coveord.atlassian.net/browse/SEARCHAPI-6018

feat(statement-groups): update group model + add filters to listing

---

src/resources/Organizations/Organization.ts
src/resources/Organizations/tests/Organizations.spec.ts

Add `pause` and `resume` to `Organization`.

feat(organization): add pause and resume calls

---

src/resources/Enums.ts
src/resources/MachineLearning/Models/ModelsInterfaces.ts

Added modelActivenessState to MLModel interface. the value is already being returned by the API. Set as optional so nothing breaking

feat(ml): added modelactivenessstate to interface

---

src/resources/License/License.ts
src/resources/License/LicenseInterfaces.ts
src/resources/License/tests/License.spec.ts
src/resources/ModifierTemplates/ModifierTemplates.ts

Fixed getter return signature, we are retrieving a list of models not only one.
I noticed the library's tests do not actually call and validate that the APIs work correctly and return the expected values. Why not call the real platform and have assertions on the results?
FOUND-3624

fix(organizationmodifier): fixed getter return signature

---

src/resources/SearchInterfaces/SearchInterfaces.model.ts
src/resources/SearchInterfaces/SearchInterfaces.ts
src/resources/SearchInterfaces/tests/SearchInterfaces.spec.ts

BREAKING CHANGE: Some interfaces has to be changed in the Admin-UI.
Because the response type changes, It could affect a few files in the Admin-UI (such as `SearchInterfaceReducer`, `SearchInterfacePreview`, `SearchInterfacesTableRow`, and so on)

feat(search-interfaces): update models and calls

---

CODEOWNERS

So, as discussed with @gdostie [here](https://coveo.slack.com/archives/C01M10DME91/p1625852537469200) because we aim to support NodeJS on the same level as a browser, and that, well, the @coveo/dx gang are the primary user of the project in a node environment, it makes sense for us to share the ownership with you to help you on that topic.
-   [x] JSDoc annotates each property added in the exported interfaces: N.A.
-   [x] The proposed changes are covered by unit tests: N.A.
-   [x] Commits containing breaking changes a properly identified as such: N.A.
-   [x] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant): N.A.

chore(codeowners): add dx gang into the fray

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

It is now possible to download the content of a snapshot in a ZIP file ([request](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Migration#/Snapshot/rest_organizations_paramId_snapshots_paramId_content_get)).
_p.s. The call is only available in platformdev at the moment._

feat(resource snapshots): export snapshot content

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

The [File](https://developer.mozilla.org/en-US/docs/Web/API/File) object is not natively supported by Node, making the `ResourceSnapshots#createFromFile` method not available to Node users (at least without hacks).
Now, the `createFromFile` method has an additional overload. It accepts files as Buffers objects.

feat: overload #createFromFile to support buffer

---

src/resources/Pipelines/StatementGroups/StatementGroupsInterfaces.ts

Added `expired` + `notStarted` counts for the StatementGroupList response.
https://coveord.atlassian.net/browse/SEARCHAPI-6068

feat(statement-groups): add new status to StatementGroupList

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

Turns out it was not a great idea to add overloads (#349).
The native [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) and the [form-data](https://www.npmjs.com/package/form-data) package are too different to create an intersection of the 2 objects.
Keeping the overloads would have created multiple manual casts and probably some refactor in other methods.
Anyway, we now have 2 methods to create a snapshot:
1. From a file
2. From a buffer
> Note: I don't consider this PR as a breaking change since the `createFromFile` method never worked on Node (even before #349).
-   [x] …

fix: create file from buffer

---

src/resources/Limits/Limits.ts
src/resources/Limits/LimitsInterfaces.ts
src/resources/Limits/tests/Limits.spec.ts

some calls were not implemented when creating settings section in react. This call should close the
loop, since some cards have history modal

feat(limits): +historyLimits for react settigns

---

src/resources/Sources/SourcesInterfaces.ts

[CTINFRA-1399]
Add property pendingCrawlingModuleId that is returned by source api. Needed because admin UI uses SourceModel instead instead of BasicSourceModel for web sources.
[CTINFRA-1399]: https://coveord.atlassian.net/browse/CTINFRA-1399

fix(sources): add missing pending Crawling Module fix to model

---

src/resources/Pipelines/Conditions/Condition.ts
src/resources/Pipelines/MLAssociations/MLAssociations.ts
src/resources/Pipelines/MLAssociations/MLAssociationsInterfaces.ts
src/resources/Pipelines/Statements/Statements.ts
src/resources/Pipelines/Statements/StatementsInterfaces.ts

Fixed `Condition.list` method return type.
before:
```ts
Promise<{
statements: StatementModel[];
totalEntries: number;
totalPages: number;
}>
```
after:
```ts
Promise<{
statements: ConditionModel[];
totalEntries: number;
totalPages: number;
}>
```

Fix list conditions return type

---

src/resources/Pipelines/StatementGroups/StatementGroupsInterfaces.ts

BREAKING CHANGE: because the campaign date parameters are now mandatory, it might create a breaking change on the actions used for the StatementGroups.
First part of this PR: https://coveord.atlassian.net/browse/SEARCHAPI-5990
set the campaignStart & campaignEnd parameters as mandatory for the creation/update of campaign.

feat(statement-groups): switch campaignStart & campaignEnd as mandatory

---

src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts

Also return the status associated to a group when listing result ranking rules
https://coveord.atlassian.net/browse/SEARCHAPI-6170

refactor(result-rankings): add associatedGroup.status to ListResultRanking

---

src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts

This reverts commit 87d23288808bab3719537faa6630f7543fb8c471.
Since my previous commit was identified as a `refactor`, it didn't trigger a new version. 
I'm reverting the commit and I'll merge it back with the `feat()` type.

revert: "refactor(result-rankings): add associatedGroup.status to ListRR"

---

src/resources/SearchInterfaces/SearchInterfaces.ts
src/resources/SearchInterfaces/tests/SearchInterfaces.spec.ts

Added a new route for sharing a search to some users.

feat(search-interface): add new route for sharing

---

src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts
src/resources/Pipelines/StatementGroups/StatementGroupsInterfaces.ts

Now that the change is in production for good, we can make the field required.
https://coveord.atlassian.net/browse/SEARCHAPI-6177

fix(result-rankings): make ResultRankingAssociatedGroupWithStatus.status mandatory

---

src/resources/License/LicenseInterfaces.ts
src/resources/Organizations/OrganizationInterfaces.ts
src/resources/Organizations/tests/Organizations.spec.ts

Added creationOrigin query parameter on organization creation call and license constants to avoid duplication and magic strings when manipulating the license properties
FOUND-3671

feat(licenseconstants): added creationOrigin query parameter

---

src/resources/Sources/Sources.ts
src/resources/Sources/SourcesDatasets/SourcesDatasets.ts
src/resources/Sources/SourcesDatasets/SourcesDatasetsInterfaces.ts
src/resources/Sources/SourcesDatasets/index.ts
src/resources/Sources/SourcesDatasets/tests/SourcesDatasets.spec.ts
src/resources/Sources/index.ts

feat(source datasets): implementation

---

Jenkinsfile.groovy

There was a rotation of credentials, and it seems the new token cannot publish anymore. I switched to the same credentials we use in admin-ui
I made the same changes that were made on the [ReactVapor](https://github.com/coveo/react-vapor/pull/2205) side.
@GermainBergeron is ok for you?
None

ci: fix the git credentials

---

Jenkinsfile.groovy

After discussion with the `dev_tooling` team, the token we use has been modified in read-only mode, this change is made to have the token in writing.

ci: use token github in writing

---

src/resources/SearchUsageMetrics/SearchHubs/SearchHubs.ts
src/resources/SearchUsageMetrics/SearchHubs/SearchHubsInterface.ts
src/resources/SearchUsageMetrics/SearchHubs/index.ts
src/resources/SearchUsageMetrics/SearchHubs/tests/SearchHubs.spec.ts
src/resources/SearchUsageMetrics/SearchUsageMetrics.ts
src/resources/SearchUsageMetrics/index.ts

Story: https://coveord.atlassian.net/browse/SEARCHAPI-6437
Based on that section on Swagger: https://platformdev.cloud.coveo.com/docs/?urls.primaryName=Search%20Usage%20Metrics#/
Added the SearchHubs interfaces and requests to be used in the Admin-UI after

feat(search-hubs): add requests and interfaces

---

src/resources/SecurityCache/SecurityCache.ts
src/resources/SecurityCache/SecurityCacheInterfaces.ts
src/resources/SecurityCache/tests/SecurityCache.spec.ts

After some discussion and to future proof.  The `usePageModel` parameter should be marked as required, true (to prevent confusion), and as deprecated, as it will be removed.
-   [] The proposed changes are covered by unit tests

fix!: send usePageModel=true for method as it is deprecated on API 

---

src/resources/Enums.ts
src/resources/Sources/SourcesSubInterfaces/Information.ts

[SRC-4649](https://coveord.atlassian.net/browse/SRC-4649)
Addition of a new attribute in the SourceStatus interface to have the live status

fix(source): new attribute extendedCurrentStatus for status

---

src/resources/MachineLearning/SmartSnippetsConfiguration/SmartSnippetsConfiguration.ts
src/resources/MachineLearning/SmartSnippetsConfiguration/SmartSnippetsConfigurationInterfaces.ts
src/resources/MachineLearning/SmartSnippetsConfiguration/tests/SmartSnippetsConfiguration.spec.ts

Added support for the following calls:
- ​/rest​/organizations​/{organizationId}​/machinelearning​/configuration​/smartsnippets​/contentfields
- ​/rest​/organizations​/{organizationId}​/machinelearning​/configuration​/smartsnippets​/documenttypes
- ​/rest​/organizations​/{organizationId}​/machinelearning​/configuration​/smartsnippets​/preview

feat(mlconfig)!: added support for ss config model preview calls

---

src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfiguration.ts
src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfigurationInterfaces.ts
src/resources/MachineLearning/CaseClassificationConfiguration/tests/CaseClassificationConfiguration.spec.ts
src/resources/MachineLearning/SmartSnippetsConfiguration/SmartSnippetsConfigurationInterfaces.ts

Added new API endpoints for Case Classification models
- Added `/fields` endpoint to get valid content field options
- Added `/preview` endpoint to get a preview of the document group validity
- Added new optional attributes to the model interface.
BREAKING CHANGES:
- renamed `DocumentRequirementStatus` to `SmartSnippetsDocumentRequirementStatus`
- changed `CaseClassificationConfiguration.baseUrl` value

feat(ml)!: added and updated Case Classification ML Config api calls

---

src/resources/Enums.ts
src/resources/MachineLearning/MachineLearning.ts
src/resources/MachineLearning/UserActionHistoryConfiguration/UserActionHistoryConfiguration.ts
src/resources/MachineLearning/UserActionHistoryConfiguration/index.ts
src/resources/MachineLearning/UserActionHistoryConfiguration/tests/UserActionHistoryConfiguration.spec.ts
src/resources/MachineLearning/index.ts
src/resources/MachineLearning/tests/MachineLearning.spec.ts

[WIP] These calls are only available in DEV for now, in the process of being released to prod
Added support for the following calls to enable/disable/get status of the User Action History ML feature:
- GET /rest/organizations/{organizationId}/machinelearning/configuration/useractionhistory
- POST /rest/organizations/{organizationId}/machinelearning/configuration/useractionhistory
- DELETE /rest/organizations/{organizationId}/machinelearning/configuration/useractionhistory
-   [X] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed …

feat(mlconfig): added support for user action history calls

---

src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts
src/resources/Search/test/Search.spec.ts

[SVCC-336](https://coveord.atlassian.net/browse/SVCC-336)
In order to be able to implement an upcoming feature, an implementer has to be able to perform a search query with the "view all content" flag.
The proposed solution is to allow passing `viewAllContent` through the existing `restQueryParameters` argument. The `viewAllContent` property is then extracted and added to the query string when needed.

feat(search): handle viewAllContent parameter

---

src/resources/UsageAnalytics/Read/Exports/Exports.ts
src/resources/UsageAnalytics/Read/Exports/ExportsInterfaces.ts
src/resources/UsageAnalytics/Read/Exports/tests/Exports.spec.ts

I've added the new api endpoint when a user wants to download an export. With this new endpoint, the access_token is no longer sent in the url

feat(exports resources): +download link export endpoint

---

Jenkinsfile.groovy

Following dblanchette recommendation to make the the shell as the right npm config before trying to publish the package to NPM
:crossed_fingers: 

ci(jenkinsfile): make sure sh config is set for npm before release

---

src/resources/MachineLearning/ModelInformation/ModelInformationInterfaces.ts

I divided it up into several interfaces. This gives flexibility but also creates many exports. If the owners would prefer I just shove them all into one interface I can do that too.

feat(ml-stats): added interfaces for case classification model stats

---

src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/tests/Pipelines.spec.ts

This information is not documented on Swagger, but you can pass a request body to the `/duplicate` call for the pipelines. To resolve a bug, this request body will be useful.

feat(pipeline): update duplicate parameters

---

src/resources/ApiKeys/ApiKeysInterfaces.ts

story: https://coveord.atlassian.net/browse/ADUI-7801
The purpose of this story is to add the additional configuration (optional) parameter to the ApiKeyModel.
I didn't export any of the new interfaces, I'm not sure it would be relevant to do so, but let me know if I should. Also, I didn't add any JSDoc (which is not ideal), because there is no description for the parameters on Swagger, so I was not comfortable to write some description that might not be accurate.
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed changes …

feat(api-keys-interfaces): add missing additional configuration

---

src/resources/ApiKeys/ApiKeysInterfaces.ts

Following this PR: https://github.com/coveo/platform-client/pull/417
It's not currently a breaking change, but I realized that some additional configuration are also optional, so I set them to be optional.

fix(api-keys-interfaces): set some parameters as being optionals

---

src/resources/UsageAnalytics/Read/DataShare/DataShare.ts
src/resources/UsageAnalytics/Read/DataShare/tests/DataShare.spec.ts

same as https://github.com/coveo/platform-client/pull/420 but I sent the POST params as body, not as query params

fix(datashare): params sent as body

---

src/resources/Enums.ts
src/resources/SearchUsageMetrics/RawMetrics/RawMetrics.ts
src/resources/SearchUsageMetrics/RawMetrics/RawMetricsInterface.ts
src/resources/SearchUsageMetrics/RawMetrics/index.ts
src/resources/SearchUsageMetrics/RawMetrics/tests/RawMetrics.spec.ts
src/resources/SearchUsageMetrics/SearchUsageMetrics.ts
src/resources/SearchUsageMetrics/index.ts
src/resources/SearchUsageMetrics/tests/SearchUsageMetrics.spec.ts

Story: https://coveord.atlassian.net/browse/SEARCHAPI-6778
This implementation is based on that documentation: https://platformdev.cloud.coveo.com/docs?urls.primaryName=Search%20Usage%20Metrics#/Raw%20Metrics
Interfaces (parameters and responses), calls and enums are added.
The enums provided are based on:
- `SearchHubLicenseMetrics` & `SearchHubLicenseType` are constants availables in the Admin-UI project, but should be exposed in Platform-client
- `SearchHubRawMetrics` is the value accepted based on the information found in the search-usage-metrics repository (service -> RawMetrics.scala)
- …

feat(raw-metrics): add interfaces, calls and enums

---

src/resources/PlatformResources.ts

In [my previous pull request](https://github.com/coveo/platform-client/pull/426) I forgot to export the new Vault resource outside of PlatformClient

fix(snapshots,vaults): export Vault outside of PlatformClient

---

src/resources/Enums.ts
src/resources/Vaults/Vaults.ts
src/resources/Vaults/tests/Vaults.spec.ts

Task: https://coveord.atlassian.net/browse/SRC-4843
This implementation is based on that documentation: https://platformdev.cloud.coveo.com/docs?urls.primaryName=Migration#/Vault/rest_organizations_paramId_vaultentries_fetch_put
Add `import` method in `Vaults` resource.

feat(vaults): add Import method

---

src/resources/Organizations/OrganizationInterfaces.ts

https://coveord.atlassian.net/browse/SVCC-507
This PR exposes the `readOnly` flag on the `status` function for the `organization` resource. This allows the caller to detect whether an organization is in the "under maintenance" state.
The JSDoc comments were added based on the [Swagger model](https://platform.cloud.coveo.com/docs?urls.primaryName=Platform#/Organizations/rest_organizations_paramId_status_get).

feat(organization): expose status readOnly flag

---

src/resources/Organizations/Organization.ts
src/resources/Organizations/tests/Organizations.spec.ts

Adding the org call created in FOUND 3921
For context, this call allows us to persist data at the organization level and is meant to accept any type of object `{}`
Use case would be to persist information for a Trial type org for instance so that we can make a call to retrieve the appropriate data across all different panels

feat(org): organization call to be added

---

src/resources/InsightPanelConfigs/InsightPanelConfig.ts
src/resources/InsightPanelConfigs/InsightPanelConfigInterfaces.ts
src/resources/InsightPanelConfigs/index.ts
src/resources/InsightPanelConfigs/tests/InsightPanelConfig.spec.ts
src/resources/PlatformResources.ts
src/resources/index.ts

https://coveord.atlassian.net/browse/SVCC-459
This PR adds the `insightPanelConfig` resource allowing a developer to invoke CRUD operations for the Insight Panel configurations.

feat(service): add insight panel config resource

---

src/resources/Catalogs/Catalog.ts
src/resources/Catalogs/CatalogInterfaces.ts

Expose cashed properties from the fieldStats endpoint response on the result from the getFieldStats function on the catalog.
Note, [the endpoint changes are only on dev](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Catalog#/Catalogs/rest_organizations_paramId_catalogs_paramId_fieldStats_get) and not yet on production. Code can be reviewed in the meanwhile. And used to develop the admin UI changes for the facet association table. **This PR can only be merged when the changes are on prod.**
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is …

feat(catalog): expose cached properties on getFieldStats result

---

src/resources/MachineLearning/ModelInformation/ModelInformationInterfaces.ts

MLX-65 is work required to use the new `contextCandidateExamples` key for a Content Recommendation model.  This adds a parameter to `ModelInformationER` interface for use.  This parameter is so the frontend will not have to parse these values to be pretty.
-   [X] JSDoc annotates each property added in the exported interfaces 
-   [ ] The proposed changes are covered by unit tests - is not covered by unit tests, as it's interface changes

feat(ml): add contextCandidateExamples to CR Model Information interface

---

src/resources/InsightPanelConfigs/InsightPanelConfig.ts
src/utils/WithRequired.ts
src/utils/index.ts

BREAKING CHANGE: optional param now required
The back-end will be requiring the `contextFields` param on UPDATE calls for Insight Panel configs so it should be enforced by the interface as well.
I added a utility interface to implement the variation. Let me know what you think.

fix(ip): updated ip config update interface

---

src/resources/MachineLearning/MachineLearningInterfaces.ts
src/resources/MachineLearning/ModelInformation/ModelInformation.ts
src/resources/MachineLearning/ModelInformation/ModelInformationInterfaces.ts
src/resources/MachineLearning/Models/Models.ts
src/resources/MachineLearning/Models/ModelsInterfaces.ts

[MLX-132](https://coveord.atlassian.net/browse/MLX-132)
The purpose of this PR is to create better return types if we know the expected ML model type, making models easier to work with.
This shouldn't make any breaking changes as far as I can tell.  It's an improvement over the existing typings and is optional to use.
I have tested this with our UI and it works as expected except our UI needs a bit of work before it can really get value from this.
| Before | After |
| ---- | ---- |
| Before we would not know what `info` is exactly. <img width="1022" alt="image" src="https://user-images.githubusercontent.com/5728044/163393399-f92b1682-7744-4957-a49d-bb97bd6298a7.png"> | If we know the expected type, we can get better Intellisense. <img width="613" alt="image" …

feat(ml): add expected return types to details endpoints

---

src/resources/Enums.ts
src/resources/License/LicenseInterfaces.ts

Task: https://coveord.atlassian.net/browse/SEARCHAPI-6904
The main objective of these changes is to add the entitlements property to the `LicenseModel` interface.
I've also added some missing JSDoc and update the type of some of the properties.

feat(license): add entitlements property to the model

---

src/resources/Enums.ts

Bug: https://coveord.atlassian.net/browse/SEARCHAPI-6934
This task: https://coveord.atlassian.net/browse/SEARCHAPI-6935
This is only to fix a type that was included in the `SearchHubLicenseMetrics` enum, in which the `recommendationQueries` value should be `recommendationsQueries`. With this update (and linking this fix to the Admin-UI), I could display the total recommendation queries value in the consumption dashboard

fix(searchhublicensemetrics): fix recommendationsQueries typo

---

pnpm-lock.yaml
src/resources/Sources/Sources.ts

I decided to change only the params at the moment of the call and not the way we use the method in order to avoid making a breaking change. Tell me if you think I should have done it otherwise.
EDIT: that param while duplicating a source never worked. But the API doesn't throws so we learned it recently.

fix(duplicate source): renamed logical index param

---

package.json

(With a valid commit)
The preinstall script is breaking the `update:platform-client` of the admin

fix(package json): preinstall script broken

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

Task: https://coveord.atlassian.net/browse/SRC-4727
This implementation is based on that documentation: https://platformdev.cloud.coveo.com/docs?urls.primaryName=Migration#/Snapshot/rest_organizations_paramId_snapshots_paramId_diff_get
Added diff endpoint for the snapshot resource.

feat(snapshot): add diff endpoint

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

A typo slipped out during my [last pull request](https://github.com/coveo/platform-client/pull/456)

fix(snapshot): interface for SnapshotDiffModel

---

src/resources/Vaults/Vaults.ts
src/resources/Vaults/tests/Vaults.spec.ts

Removed `currentOrganizationId`. The API does not accept such query parameter. The role described by `currentOrganizationID` is actually played by the `API.orgPlaceholder` in the `baseUrl` of the resource.
Ergo, one should initialize its platformclient with the `currentOrganizationId` as its organizationId to do actually what the function was describing.
Removing the param remove this confusion. It is also a breaking change because the removed parameter is not the last, so existing calls will break.
-   [x] JSDoc annotates each property added in the exported interfaces: N.A.
-   [x] The proposed changes are covered by unit tests: adapted
-   [x] Commits containing breaking changes a properly identified as such: yep, see the `!`
-   [x] …

fix(vault)!: remove useless arg from /import

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

It's not yet in dev but it will happen very quickly.
The Diff method will be entitled to a new parameter, it is a limit to know how to build the URL.
- if the number of data is less than the limit, the url returns the file to view
- if the number of data is greater than the limit, the url forces the download of this file
API Doc => https://platformdev.cloud.coveo.com/docs?urls.primaryName=Migration#/Snapshot/rest_organizations_paramId_snapshots_paramId_diff_get
-   [x] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed changes (if …

feat(snapshot): add new parameter for diff method

---

src/resources/SearchUsageMetrics/SearchHubs/SearchHubs.ts
src/resources/SearchUsageMetrics/SearchHubs/SearchHubsInterface.ts
src/resources/SearchUsageMetrics/SearchHubs/tests/SearchHubs.spec.ts

Story: https://coveord.atlassian.net/browse/SUMS-222
This branch is to add a parameters interface for the list API call, as there is now some optional parameters available for this request + add the `totalCount` parameter to the list call's response.

feat(search-hubs): update interfaces and add list params

---

src/resources/Sources/Sources.ts
src/resources/Sources/SourcesMetadata/SourcesMetadata.ts
src/resources/Sources/SourcesMetadata/SourcesMetadataInterfaces.ts
src/resources/Sources/SourcesMetadata/index.ts
src/resources/Sources/SourcesMetadata/tests/SourcesMetadata.spec.ts

[CTINFRA-2754](https://coveord.atlassian.net/browse/CTINFRA-2754) :rocket: 
Add an API to retrieve the metadata of a Source.

feat(source): add call to list all metadata for a source

---

src/resources/SecurityCache/SecurityCache.ts
src/resources/SecurityCache/SecurityCacheInterfaces.ts
src/resources/SecurityCache/tests/SecurityCache.spec.ts

Added support for new Security Cache list call that allows to search and filter for an identity name
and/or a specific type, this call will live alongside the exisiting one for now but in the future
all options will come together in the new call and the old one will be deprecated.

feat(securitycache): new list call with identity name & type filters

---

src/resources/Sources/SourcesMetadata/SourcesMetadata.ts
src/resources/Sources/SourcesMetadata/SourcesMetadataInterfaces.ts

[CTINFRA-2773]
Change the model for the metadata of a source. 
[CTINFRA-2773]: https://coveord.atlassian.net/browse/CTINFRA-2773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(metadata): edit metadata model

---

src/resources/Sources/SourcesMetadata/SourcesMetadataInterfaces.ts

[CTINFRA-2822]
Handles a new boolean returned by the Source Metadata Service, that indicates if the feature can be leveraged at all for a source.
[CTINFRA-2822]: https://coveord.atlassian.net/browse/CTINFRA-2822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(metadata): add sample available boolean

---

src/resources/Search/SearchInterfaces.ts

[`maximumTimeoutMs` was spelled incorrectly and had it `maximumTimeOutMs`](https://platformdev.cloud.coveo.com/docs/?urls.primaryName=Search%20API#/Search%20V2/searchUsingPost)
(changed commit message - removed breaking change)

fix(search): update the interface key property `maximumTimeoutMs` case

---

src/resources/ResourceSnapshots/ResourceSnapshotsInterfaces.ts

The diff response can contain only a subset of resources, hence the `Partial<>`.
It can also return an empty object.

fix: set snapshot diff files as partial record

---

src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfigurationInterfaces.ts
src/resources/MachineLearning/CaseClassificationConfiguration/tests/CaseClassificationConfiguration.spec.ts
src/resources/MachineLearning/FilterConditions.ts

[MLX-86]
Restore an enum that was deleted in a previous version of the platform client (while still being used by the admin-UI). This will allow bumping the platform client in the admin UI once more.
[MLX-86]: https://coveord.atlassian.net/browse/MLX-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(platform-client): revert enum removal

---

src/resources/Pipelines/PipelinesInterfaces.ts

JIRA Task: https://coveord.atlassian.net/browse/SEARCHAPI-7228
In this PR, I am adding new properties to `PipelinesInterfaces` as new optional properties have been added in regards to the [Query Pipeline Overview Revamp](https://coveord.atlassian.net/browse/SEARCHAPI-7043).  I've also added missing JSDoc in this file. 
See [Swagger](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Pipelines/createQueryPipelineV1) for more information.
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed changes (if …

feat(pipelines-interfaces): update interface to add newly created properties

---

CODEOWNERS

Now, with auto attribution to both teams.
See example https://github.com/coveo/testing-codweownersfile/pull/2

chore(codeowners): fix codeowners file

---

.github/workflows/cd.yml

Replaced by the proper env var name
see why: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
You can also look up NODE_AUTH_TOKEN on org:coveo, you'll see it being used elsewhere too. (oopsie, should have been more careful)

chore: fix cd flow bad env variable

---

src/resources/Connectivity/Connectivity.ts
src/resources/Connectivity/ConnectivityInterface.ts
src/resources/Connectivity/tests/Connectivity.spec.ts

Add a query param for the create log request call. 

feat(connectivity): add resourceType param to createLogRequest

---

src/resources/Pipelines/ResultRankings/ResultRankingsInterfaces.ts

Based on this documentation: https://platformdev.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Result%20rankings/getResultRankingRule, it seems that the _ResultRankingTargetLocalizedContent_ interface need to be updated. The _ResultRankingLocalizedContent_ and the _ResultRankingLocalizedContentLocaleSpecific_ were also to be updated.

fix(result-rankings-interfaces): update localizedContent part

---

src/resources/Activities/Activities.ts
src/resources/Activities/ActivitiesInterfaces.ts
src/resources/Activities/index.ts
src/resources/Activities/tests/Activities.spec.ts
src/resources/PlatformResources.ts

Added a new Resource class for the Activities with the following calls:
- GET (an activity for an id)
- GET  resourcetype
- list (POST) activities
- list (POST) facets activities
- search (POST) activities (the list is said to be deprecated hence the need for search)
- searchfacet (POST) activities (the list is said to be deprecated hence the need for search)
- cancelActivity (PUT) to cancel the activity
I instantiated the new resource on the base PlatformResources.ts and wrote the unit tests for the calls.
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is …

Feat client platform add activities resources

---

src/resources/Pipelines/Statements/Statements.ts
src/resources/Pipelines/Statements/StatementsInterfaces.ts
src/resources/Pipelines/Statements/tests/Statements.spec.ts

[KIT-2096](https://coveord.atlassian.net/browse/KIT-2096)
Add support for `bulkGet` statements API for query pipelines: https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Statements%20V2/bulkGetStatementsOperationV2

feat: add support for bulkGet query pipeline statements

---

src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/PipelinesInterfaces.ts

The list pipelines API added (a long time ago) a parameter to specify that the call should be paginated, in a backward compatible way.
If the parameter `enablePagination` is not specified or set to false, the API returns a list: `PipelineModel[]`
If `enablePagination=true`, then the API return an object with `{items: PipelineModel[], totalEntries: number}` 

feat: add support for list pipelines with pagination enabled

---

src/resources/Activities/Activities.ts
src/resources/Activities/tests/Activities.spec.ts

Fixed an issue in the Activities Resources.
Removed the 'Public' from the urls for the calls. Also adjusted the unit tests for those calls

fix(activities): fixed API calls for activities, removing public in URL

---

src/resources/Catalogs/ProductListingConfigurationInterfaces.ts
src/resources/Catalogs/tests/ProductListingConfiguration.spec.ts

Added new `name` field to `RankingConfiguration` interface

feat(product-listing): add name field to ranking configuration interface

---

src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts

Windows is using `application/x-zip-compressed` instead of the standard `application/zip` :finnadie:.
If we don't support it, we go into the 'default' clause of the switch and the snapshot upload doesn't work on Windows.
**BONUS:** For the duration of the Centraide Campain 2022, author of unconventional commit on master will …

fix(snapshot): support windows silly mime-type

---

.eslintrc.js
.husky/commit-msg
.husky/pre-commit

After I finished my work, meticulously going over the Read service resources, I wasn't able to commit my work. Luckily the error pointed me towards it being an issue with husky:
> error: cannot spawn .husky/pre-commit: No such file or directory
After searching the internet I found that putting the `#!/bin/sh` shebang in the commit hook files solves the issue. Probably because it is using a different execution environment by default on Windows, which fails.
<details><summary>Reverted after feedback</summary>
<p>
To start working on the Read service resource definitions, I pulled in this repository. Only to be greeted with every single line in every TS file having an error. It asked me to remove the `CR` character on every line.
I found this [StackOverflow about …

build: fix commit hook on windows

---

src/resources/CrawlingModule/CrawlingModuleInterfaces.ts

[CTINFRA-3117]
A new possible state for Crawling Module Log Requests should be supported, EMPTY. This is a log request that *was* processed, but no log was found for it locally.
[CTINFRA-3117]: https://coveord.atlassian.net/browse/CTINFRA-3117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(maestro): support empty crawling module log requests

---

src/resources/Enums.ts
src/resources/UsageAnalytics/Read/Administration/Administration.ts
src/resources/UsageAnalytics/Read/Administration/AdministrationInterfaces.ts
src/resources/UsageAnalytics/Read/Administration/tests/Administration.spec.ts
src/resources/UsageAnalytics/Read/CommonParamParts.ts
src/resources/UsageAnalytics/Read/Dimensions/Dimensions.ts
src/resources/UsageAnalytics/Read/Dimensions/tests/Dimensions.spec.ts
src/resources/UsageAnalytics/Read/Exports/Exports.ts
src/resources/UsageAnalytics/Read/Exports/tests/Exports.spec.ts
src/resources/UsageAnalytics/Read/Filters/Filters.ts
src/resources/UsageAnalytics/Read/Filters/FiltersInterfaces.ts
src/resources/UsageAnalytics/Read/Filters/tests/Filters.spec.ts
src/resources/UsageAnalytics/Read/ReadServiceCommon.ts
src/resources/UsageAnalytics/Read/Reports/Reports.ts
src/resources/UsageAnalytics/Read/Reports/ReportsInterfaces.ts
src/resources/UsageAnalytics/Read/Reports/tests/Reports.spec.ts
src/resources/UsageAnalytics/Read/Statistics/Statistics.ts
src/resources/UsageAnalytics/Read/Statistics/StatisticsInterfaces.ts
src/resources/UsageAnalytics/Read/Statistics/tests/Statistics.spec.ts
src/resources/UsageAnalytics/Read/Users/Users.ts
src/resources/UsageAnalytics/Read/Users/UsersInterfaces.ts
src/resources/UsageAnalytics/Read/Users/tests/Users.spec.ts
src/resources/UsageAnalytics/Read/index.ts

This is basically a continuation of what I started in #581, but these are the breaking changes I took note of during my pass over the existing resources:
- Rename most health and status check calls, change return types of all. I created an interface to enforce the calls to be aligned, and re-use the doc.
_I realize it makes the diff a bit more annoying, but I also moved the health and status check to the end of each resource, putting them in that order. (Same for the test files)._
- Remove the `setRedshiftStatus` method (that is not on the back-end service anymore)
- Fix some various minor mis-typing
- Remove deprecated methods from the Statistics API.
Of course, any of these changes may lead integrators to have type conflicts/missing method calls. I manually tested a built version of …

refactor(ua read): breaking api alignment & fixes

---

src/resources/UsageAnalytics/Read/Dimensions/Dimensions.ts
src/resources/UsageAnalytics/Read/Dimensions/DimensionsInterfaces.ts

The listUncreatedDimension was not returning the right data format (it was missing the suggestions layer)
```
suggestions: subObject[] <--- tight now it's only returning subObject[] from the call
```
So I've added the layer with `suggestions` so we can use this call with the api name autocomplete feature
-   [ ] …

Ua 6254 fix dimensions suggestions call

---

.eslintignore
jest.config.mjs
package-lock.json
package.json
scripts/dualOutputCompat.js
src/resources/Resource.ts
tsconfig.build.cjs.json
tsconfig.build.esm.json
tsconfig.build.json
tsconfig.json

Reestablish support for CJS.
⚠️this is a temporary fix, ESM only is inevitable⚠️ 
Users can shift from CJS to ESM and vice-versa without changing anything in their code.

feat: support CJS and ESM

---

renovate.json

We don't want `query-string-cjs` to update.

chore(renovate): block query-string-cjs updates

---

src/resources/Sources/SourcesMetadata/SourcesMetadataInterfaces.ts

* Renamed `frequency` property of the interface `Metadata` with `count`.
Items of type `Metadata` seem to contain a `count` property instead of `frequency`.
Result when testing the API:

feat(metadata): rename frequency property for count in Metadata interface

---

src/resources/Sources/SourcesMetadata/SourcesMetadataInterfaces.ts

Add `indexedBy` for the Metadata interface
[DISCO-9]: https://coveord.atlassian.net/browse/DISCO-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

feat(metadata): add indexedBy for Metadata interface

---

src/resources/InProductExperiences/InProductExperiencesInterfaces.ts

[SVCINT-2087](https://coveord.atlassian.net/browse/SVCINT-2087)
This field was always present, but never defined in the interface.
[SVCINT-2087]: …

fix: add buttonTargetSelector field

---

src/resources/IPXInterfaces/IPXInterface.model.ts

Update the IPX definition based on the latest changes

fix: update IPX definition

---

src/resources/CrawlingModule/CrawlingModuleInterfaces.ts

[CTINFRA-3207]
typo in logRequestsEnable for CrawlingModuleStatus interface
[CTINFRA-3207]: https://coveord.atlassian.net/browse/CTINFRA-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

fix(crawling-module): typo in logRequestsEnable for CrawlingModuleStatus interface

---

src/Endpoints.ts
src/tests/Endpoint.spec.ts

Adds canada region to Endpoints.ts, in order to support the region in the Admin UI.
[CTINFRA-3203]
[CTINFRA-3203]: https://coveord.atlassian.net/browse/CTINFRA-3203?atlOrigin=eyJpIjoiNWRk …

fix(platform): add Canada support to platform-client

---

src/resources/Extensions/Extensions.ts

I added the `validateScript` call in this previous [PR](https://github.com/coveo/platform-client/pull/627) but made a mistake when precising its return value.
* Corrected the `validateScript` call's return type from `ExtensionCompileCode` to `ExtensionCompileResult` (see [Swagger](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Extension#/Indexing%20Pipeline%20Extensions/rest_organizations_paramId_extensions_test_compile_post)).
-   [ ] …

refactor(extensions): correct validateScript's return type

---

src/resources/Enums.ts
src/resources/OrganizationAccess/AccessInterfaces.ts

https://coveord.atlassian.net/browse/CTCORE-9017
BREAKING CHANGE: Adjusted wrong AccessModel interface
* fix: PrivilegeholderType enum got renamed to PrivilegeHolderType
* fix: the AccessLevel property is not an array anymore
* fix: added missing properties to the AccessModel interface
The AdminUi repo is adjusted to match this PR. I'll update the platformClient dependency once this PR is merged and create the PR to fix this in the AdminUi.
-   [ ] …

[CTCORE-9017] fix(Privilege): fix wrong access model interface definition

---

src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Catalogs/tests/Catalog.spec.ts

Update interfaces to follow recent swagger changes [COMSDZ-300](https://coveord.atlassian.net/browse/COMSDZ-300)
- make some parameters optional on the [CatalogConfiguration](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Catalog#/Catalog%20Configurations/rest_organizations_paramId_catalogconfigurations_paramId_get:~:text=CatalogConfigurationModelWithAssociatedCatalogs,CatalogConfigurationModelWithAssociatedCatalogs)
- add configuration to the [CreateCatalogModel](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Catalog#/Catalogs/rest_organizations_paramId_catalogs_post:~:text=CreateCatalogModelReq,CreateCatalogModelReq) and add a deprecated note to the other parameters 
-   [X] My changes are publicly available, documented, and deployed in production. (i.e. on …

refactor(catalogs): add configuration to create catalog model

---

src/resources/Limits/Limits.ts
src/resources/Limits/tests/Limits.spec.ts

* Added the `getSpecificLimitStatus` call (see [Swagger](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Platform#/Limits/rest_organizations_paramId_limits_paramId_paramId_get)). …

feat(limits): add call to retrieve a specific limit status

---

CONTRIBUTING.md
src/APICore.ts
src/handlers/ResponseHandlerInterfaces.ts
src/handlers/ResponseHandlers.ts
src/resources/InsightPanelConfigs/InsightPanelConfigInterfaces.ts
src/resources/MachineLearning/ModelConfiguration/ModelConfiguration.ts
src/resources/MachineLearning/ModelConfiguration/tests/ModelConfiguration.spec.ts
src/resources/Pipelines/ResultRankings/ResultRankings.ts
src/resources/Pipelines/ResultRankings/tests/ResultRankings.spec.ts
src/resources/PushApi/PushApi.ts
src/resources/PushApi/tests/PushApi.spec.ts
src/tests/APICore.spec.ts
src/utils/Retriever.ts
src/utils/WithRequired.ts
src/utils/createFetcher.ts
src/utils/index.ts
src/utils/types.ts

I wrote a custom React hook in admin-ui, that will actually abort requests instead of ignoring the result (which is what `useAsyncFn` and alike tend to do). The resource for this is not in this repository yet, as it is pending completion. (The Data Health resource definition is currently added to admin-ui, until the service endpoint is finalized and we can add it here properly).
This resource definition has direct access to the "api", and I immediately saw issue when passing a `RequestInit` object with a `signal` on it: the (http) `method` is no longer set. That is why I decided to log [UA-7571](https://coveord.atlassian.net/browse/UA-7571).
The short summary is that default arguments where used to provide the "predefined" method, body et cetera. But if you specify your own arguments, …

fix(core): support user requestinit arguments

---

src/resources/Enums.ts
src/resources/SecurityCache/SecurityCache.ts
src/resources/SecurityCache/SecurityCacheInterfaces.ts
src/resources/SecurityCache/tests/SecurityCache.spec.ts

Just adding a new filter for `SecurityCache.listSecurityProviderIdentities` call
Task: [CTCORE-9140](https://coveord.atlassian.net/browse/CTCORE-9140)
Swagger: [/rest/organizations/{organizationId}/securitycache/entities/list](https://platformdev.cloud.coveo.com/docs?urls.primaryName=SecurityCache#/Security%20Cache/rest_organizations_paramId_securitycache_entities_list_post)
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README. …

feat(securityCache): added FilteringMode attribute for SecurityCache.listSecurityProviderIdentities

---

src/resources/SecurityCache/SecurityCache.ts
src/resources/SecurityCache/tests/SecurityCache.spec.ts

Added corresponding method for call isListSecurityIdentitiesSupported

feat(securityCache): added call isListSecurityIdentitiesSupported

---

src/resources/MachineLearning/IAPRConfiguration/IAPRConfiguration.ts
src/resources/MachineLearning/IAPRConfiguration/IAPRConfigurationInterfaces.ts
src/resources/MachineLearning/IAPRConfiguration/index.ts
src/resources/MachineLearning/IAPRConfiguration/tests/IAPRConfiguration.spec.ts
src/resources/MachineLearning/MachineLearning.ts
src/resources/MachineLearning/index.ts
src/resources/MachineLearning/tests/MachineLearning.spec.ts

feat(iapr api call): post call for creating iapr model

---

src/Entry.ts

Re-export the default export of Endpoints so it can be publicly accessed by external packages. Replaces #667.

feat(endpoints): expose Endpoints default export

---

src/resources/MachineLearning/MachineLearningInterfaces.ts
src/resources/MachineLearning/Models/ModelsInterfaces.ts

Add an interface for model's extraConfig, previously it uses `[key: string]: any` which is not very clear

feat(ml): Define interface for Model's extraConfig

---

src/resources/Pipelines/Statements/Statements.ts
src/resources/Pipelines/Statements/tests/Statements.spec.ts

Relates to the build failure of #678 
Based on W3C spec & MDN:
- https://developer.mozilla.org/en-US/docs/Web/API/FormData/append
- https://xhr.spec.whatwg.org/#dom-formdata-append
- https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set
the 3rd arg is ignored when the 2nd is a string.
proof of bug: 
https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhjAvDMBTA7jAYiATgWwBE4o4AKASgG4AoAejpgAEoIBaASwHMw9Ua4AOjgAHEajAATMgHIAZhwA2qGQBoYMkSFJQQajVp16KNGqEghlgxSC5khEqLg6oIlCkA
-   [x] …

fix(pipeline): do not set filename when appending a str

---

src/resources/Fields/Fields.ts
src/resources/Fields/tests/Fields.spec.ts
src/resources/Resource.ts

Fixes #684
search is a post, put those params in the body.

fix(field): search should send param in body

---

src/APICore.ts
src/handlers/ResponseHandlerInterfaces.ts
src/handlers/ResponseHandlers.ts
src/handlers/tests/ResponseHandlers.spec.ts
src/resources/Pipelines/Statements/Statements.ts
src/resources/Pipelines/Statements/tests/Statements.spec.ts
src/resources/ResourceSnapshots/ResourceSnapshots.ts
src/resources/ResourceSnapshots/tests/ResourceSnapshots.spec.ts
src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts
src/resources/Search/test/Search.spec.ts
src/tests/APICore.spec.ts
src/utils/types.ts

Adding the [`GET /rest/search/v2/html`](https://docs.coveo.com/en/13/api-reference/search-api#tag/Search-V2/operation/htmlGet) endpoint on the `Platform.search` resource.
Usage:
```ts
const html = await Platform.search.previewHTML({uniqueId: '🆔'});
```
~#### Disclaimer 1~
~I had to modify the default `success` response handler, because it would parse any response as JSON. This particular endpoint's response is `text/html`, therefore it cannot be parsed as JSON.~
~To circumvent this issue, I added a condition to only call `response.json()` if the `Content-Type` header matches `application/json`. In the opposite case it will call `response.text()` instead. I am aware this solution isn't perfect, but it is in fact a step in the right direction considering what we were doing.~
⬆️ Fixed by …

Add search /html endpoint

---

src/APICore.ts
src/tests/APICore.spec.ts

This fix makes sure `responseBodyFormat` argument reaches the response handlers. The `args` object was getting mutated by the call to `delete`, preventing `responseBodyFormat` argument to have any value other than `'json'` when reaching the response handlers. Added some missing UT coverage for it.
-   [x] My merge …

fix(APICore): forward responseBodyFormat to response handlers

---

src/resources/Pipelines/Statements/Statements.ts

`statements.exportCSV` method should return a `Blob`, not a `Record<string, unknown>`.
My bad, it was a small overlook on my part related to the new `responseBodyFormat` argument.

fix(statements): fix exportCSV return type

---

src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts

I noticed the `search.query` method had `Promise<any>` return type, which is pretty annoying since its one of if not the most important coveo API in terms of customer facing value. In this PR I added all the necessary types and jsdocs to properly type the return of this method according to [this documentation](https://docs.coveo.com/en/13/api-reference/search-api#tag/Search-V2/operation/searchUsingPost).
-   [x] …

fix(search)!: add search.query response types

---

src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts
src/resources/Search/test/Search.spec.ts

Adding the `search.getDocument` method which retrieves a single item from the index using its `uniqueId`

feat(search): add getDocument method

---

src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts
src/resources/Search/test/Search.spec.ts

Add endpoint to search facet values for a given facet.
See the endpoint in [Swagger](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Search%20V2/facetSearch).
🎬 Linked `platform-client` to my local `admin-ui` instance and plugged the endpoint with the search action of a facet.
⚠️ For the purpose of this test, I didn't make it so the list reflected the API call's results. I only inspected the network tab to make sure the results returned looked good.
https://github.com/coveo/platform-client/assets/133259861/98431de8-321e-4d1e-90a2-576186f2dca9
- See the endpoint in [Swagger](https://platform.cloud.coveo.com/docs?urls.primaryName=S …

feat(search, facet): add endpoint to search facets

---

src/resources/UsageAnalytics/UsageAnalytics.ts

Add missing entry to UsageAnalytics resource class
[UA-8052]: https://coveord.atlassian.net/browse/UA-8052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …

fix: add dataHealth to UsageAnalytics resource class

---

src/resources/InsightPanelConfigs/InsightPanelConfig.ts
src/resources/InsightPanelConfigs/InsightPanelConfigInterfaces.ts
src/resources/InsightPanelConfigs/tests/InsightPanelConfig.spec.ts

[SVCC-3139](https://coveord.atlassian.net/browse/SVCC-3139)
Add insight panel duplication config route of the following route: 
`/organizations/:organizationId/insightconfig/v1/configs/:configId`
with a body as:
`{
name: string;
}` …

feat(insight): add duplicate config route

---

src/resources/MachineLearning/ModelInformation/ModelInformationInterfaces.ts

To fix this issue [MLX-556](https://coveord.atlassian.net/browse/MLX-556)
[MLX-556]: https://coveord.atlassian.net/browse/MLX-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

fix(MLX):  add ModelInformationPQS interface

---

src/resources/PlatformResources.ts
src/resources/Projects/Project.ts
src/resources/Projects/ProjectInterfaces.ts
src/resources/Projects/index.ts
src/resources/Projects/tests/Project.spec.ts
src/resources/Resources/Resources.ts
src/resources/Resources/ResourcesInterfaces.ts
src/resources/Resources/index.ts
src/resources/Resources/tests/Resources.spec.ts
src/resources/index.ts

* Created a new `Resource` class called `Project`;
* Created a new `Resource` class called `Resources`;
* Created the basic CRUD operations of the [Workspace service](https://platform.cloud.coveo.com/docs?urls.primaryName=Workspace), such as `list`, `create`, `update`, `get` and `delete`;
* Created the necessary interfaces for these operations;
* Instantiated the new classes in `PlatformResource`.
-   [ ] …

feat(workspace): add CRUD operations for projects and resources

---

src/resources/Resource.ts
src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts
src/resources/Search/test/Search.spec.ts

Making a few corrections to the `Search` API calls to `/document` and `/html` endpoints:
- Added missing query parameters on `getDocument` (they were missing on the swagger doc as well, see SEARCHAPI-8913)
- Allow to pass in the empty pipeline as parameter to `getDocument` (previously empty string query params we're removed so it was not possible)
- Use POST endpoint for `previewHTML` instead of GET. Allows to pass in the full rest parameters in the body, which unlocks all the available features of this endpoint.
I also cleaned up the interfaces a bit by declaring a shared params interface and reusing it where possible. This way we avoid having to repeat the lengthy jsdocs everywhere. Still not perfect, but now we have a few repetitions less 🤷 
-   [x] My changes are publicly available, …

fix(resource): allow empty string as query param value

---

src/resources/Projects/Project.ts
src/resources/Projects/tests/Project.spec.ts
src/resources/Resources/ResourcesInterfaces.ts

Added a new endpoint that retrieves resources by status for a given project (see [Swagger](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Workspace#/Projects/rest_organizations_paramId_projects_paramId_resources_get) for more details).
-   [x] My merge commit message will be conventional (See …

feat(workspace): add new endpoint to retrieve resources by status

---

src/resources/Search/Search.ts
src/resources/Search/test/Search.spec.ts

[SEARCHAPI-9086](https://coveord.atlassian.net/browse/SEARCHAPI-9086)
We need to be able to pass the empty pipeline to this call otherwise it's the default pipeline being used when no parameters are passed.
-   [X] My merge commit message will be conventional (See [Conventional …

fix(resource): fix search list fields to allow empty pipeline

---

src/resources/Enums.ts

[SEARCHAPI-9039](https://coveord.atlassian.net/browse/SEARCHAPI-9039)
Add missing ML model types in `Enum.ts`. 
- `IntentAwareProductRanking = 'intentranking'`
- `RelevanceGenerativeAnswering = 'genqa'`
- `SemanticSearch = 'embeddings'`
I looked in the [backend](https://github.com/coveo/ml-config-service/blob/master/coveo-cloud-ml-config-server/src/main/java/com/coveo/cloud/mlconfig/services/MLWorkflowNameConstant.java) to confirm the values.
I also had a discussion with UI ML team about it. They told me they have a duplicated enum in the [admin-ui](https://github.com/coveo/admin-ui/blob/master/pages/model/src/constants/ModelConstants.ts#L34).
-   [ …

feat(ml): add missing model types for genqa

---

CONTRIBUTING.md

Added a "Scope" section in CONTRIBUTING.md. 
Lately, and in the past just generally, we have often been explaining the same thing over and over during the review process. Basically that things that aren't public or stable shouldn't be exposed in the client. 
The goal of this section is to avoid contributors spending time to do their pull request just to be sent back to their project when they get at the review stage. It will also to avoid having to repeat ourselves and just point to that doc when needed. It will make expectations clearer for everyone in general. 
-   [ ] The …

docs(contributing): explain project scope explicitly

---

src/resources/Enums.ts
src/resources/Sources/SourcesInterfaces.ts
src/resources/Sources/tests/Sources.spec.ts

CTCORE-9562
This PR adds the new stringFilterType param to the `ListSourcesParams` interface with accompanying `StringFilterType` enum. 

feat(sources): add StringFilterType enum

---

src/resources/Search/Search.ts
src/resources/Search/SearchInterfaces.ts

https://platform.cloud.coveo.com/docs/?urls.primaryName=Search%20API#/Search%20V2/valuesGet

fix(search): properly type getFieldValues return type

---

src/resources/IPXInterfaces/IPXInterface.ts
src/resources/IPXInterfaces/tests/IPXInterface.spec.ts
src/resources/NextGenSearchPages/NextGenSearchPages.model.ts
src/resources/NextGenSearchPages/NextGenSearchPages.ts
src/resources/NextGenSearchPages/index.ts
src/resources/NextGenSearchPages/tests/NextGenSearchPages.spec.ts
src/resources/PlatformResources.ts
src/resources/index.ts

SVCINT-2683
Goes with [this PR](https://github.com/coveo/search-interface-service/pull/1378)

SVCINT-2683 feat: add next gen search page API

---

src/resources/MachineLearning/SmartSnippetsConfiguration/SmartSnippetsConfiguration.ts
src/resources/MachineLearning/SmartSnippetsConfiguration/SmartSnippetsConfigurationInterfaces.ts
src/resources/MachineLearning/SmartSnippetsConfiguration/tests/SmartSnippetsConfiguration.spec.ts

remove SmartSnippets CRUD endpoints, CRUD operation of this model will be using /rest/organizations/{organizationId}/machinelearning/model instead
BREAKING CHANGE: remove SmartSnippets CRUD endpoint
There are 4 endpoints deprecated from machine learning configuration:
https://platform.cloud.coveo.com/docs?urls.primaryName=Machine%20Learning%20Configuration#/Smart%20Snippets%20Configuration/rest_organizations_paramId_machinelearning_configuration_smartsnippets_model_paramId_get
-   [x] Commits containing breaking changes a …

feat(ml): remove SmartSnippets CRUD endpoint

---

src/APICore.ts
src/tests/APICore.spec.ts

As we can see here https://github.com/coveo/platform-client/blob/master/src/APICore.ts#L73, when a request is aborted, the client resolves the promise with `undefined`. This is a wrong approach to handling abort errors, because we are essentially lying to the caller. For example, the return type could be something like `Promise<PageModel<Something>>`, but in reality we can return `Promise<undefined>` when an abort occurs. Since the type declaration does not reflect that `undefined` is a possible return value, the code in user land can't know it must handle that edge case.
`AbortError` will now be thrown instead of catching it and resolving the `GET` request with `undefined`. This is a more natural way of handling abort errors. We let the user take care of how it should be done. If the …

fix(APICore): let AbortError be thrown

---

src/resources/PushApi/PushApi.ts
src/resources/PushApi/PushApiInterfaces.ts
src/resources/PushApi/tests/PushApi.spec.ts

https://coveord.atlassian.net/browse/DT-6757
This PR adds a new method the `PushApi` resource to allow the creation of file containers.

feat(pushapi): add method to create a file container

---

src/resources/Catalogs/CatalogInterfaces.ts

CTCORE-9876
This adds `catalogIds` and `sourceIds` to the CatalogsListOptions to reflect the new parameters in the Swagger: 
Can anyone clarify whether this is a breaking change or not?

feat(catalogs): add catalogIds and sourceIds to CatalogsListOptions

---

src/resources/Pipelines/PipelinesInterfaces.ts
src/resources/Pipelines/tests/Pipelines.spec.ts

Add the `excludeAbTestTargets` parameters to the `ListPipelinesOptions` interface. 
This property is documented in [Swagger](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Pipelines/listQueryPipelinesV1). 📖 

feat(pipelines): add excludeAbTestTargets parameter to options

---

src/resources/Catalogs/CatalogContent.ts
src/resources/Catalogs/CatalogInterfaces.ts

Add interface for your new api 

fix: add interface for catalogContent

---

src/resources/Pipelines/Statements/Statements.ts
src/resources/Pipelines/Statements/tests/Statements.spec.ts

https://coveord.atlassian.net/browse/SEARCHAPI-9775
Add the `statements/bulkDelete` endpoint. It allows to delete multiple statements from a query pipelines at once.
It's documented in Swagger [here](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Statements%20V2/bulkDeleteStatements). 📖 
I also took the liberty to add the missing jsDoc to the other endpoints in that resource. 
Documentation for those endpoints is at the same place as the new endpoint above (under `Statements V2`) [here](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20API#/). 📖  
-   [X] JSDoc annotates each property added in the exported …

feat(statements): add bulkDelete endpoint for pipeline statements

---

src/resources/Projects/ProjectInterfaces.ts

[TSP-214](https://coveord.atlassian.net/browse/TSP-214)
[TSP-214]: https://coveord.atlassian.net/browse/TSP-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …

feat(projects): add new project types

---

src/resources/Catalogs/CatalogInterfaces.ts

[CIUG-771](https://coveord.atlassian.net/jira/software/c/projects/CIUG/boards/1054?selectedIssue=CIUG-771)
Add a param `enrichWithFields` 
[CIUG-771]: …

feat: add new param to bypass field enrichements on list catalogs

---

.github/actions/merge-commit/action.yml
.github/workflows/ci.yml

This PR is a shot in the dark, no idea if it'll actually work, but I think we can leverage some special behavior from the merge queue to actually "see" the merge commit before it reaches master, and validate it.

chore: use merge queue to validate commit message

---

.github/workflows/dependency-review.yml
src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Pipelines/Pipelines.ts
src/resources/Pipelines/PipelinesInterfaces.ts

Add new interface for response object of the `/rest/search/v1/admin/pipelines/{pipelineId}` endpoint since a new property was added in the response of that endpoint specifically.
See for yourself in [Swagger](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Pipelines/getQueryPipelineV1). 📖 

feat(pipelines): add new interface for get single pipeline

---

.github/workflows/codeql.yml

The CodeQL action doesn't seem to support merge queues yet. See this issue: https://github.com/github/codeql-action/issues/1537
See this discussion for the workaround: https://github.com/orgs/community/discussions/46757#discussioncomment-7768838
Basically we make sure the CodeQL status check is run the PR only.

chore(ci): workaround for CodeQL in merge queues

---

src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfiguration.ts

The following endpoints : Create, Delete, Get, Update
Are no longer to be used through the case classification API. 
A PR has been merged and will be shipped before this one (Opening this PR a bit early so that you guys can review). The PR adds the deprecation warnings on swagger https://github.com/coveo-platform/ml-config-service/pull/2090
-   [x] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the …

docs(caseclassificationconfiguration): add deprecation warnings

---

src/resources/Catalogs/CatalogContent.ts
src/resources/Catalogs/tests/CatalogContent.spec.ts

removed version number in catalog content api call
since the old call is deprecated, and the new call is already being used in prod, we longer need a version number to make the difference …

feat: remove version number in get objecttype call

---

src/resources/Projects/Project.ts
src/resources/Projects/ProjectInterfaces.ts
src/resources/Projects/tests/Project.spec.ts

Added this new [endpoint](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Workspace#/Projects/rest_organizations_paramId_projects_resources_ids_post)
* This endpoint gets the associated project ID(s) per provided resource ID(s);
* Takes the `org ID`, the `resource type` of the provided resourced ID(s) as params, and the resource IDs in the body.
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to …

feat(project): add new endpoint

---

src/resources/MachineLearning/CaseClassificationConfiguration/CaseClassificationConfigurationInterfaces.ts
src/resources/MachineLearning/CaseClassificationConfiguration/tests/CaseClassificationConfiguration.spec.ts

The [call](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Machine%20Learning%20Configuration#/Case%20Classification%20Configuration/rest_organizations_paramId_machinelearning_configuration_caseclassif_fields_post) to receive the fields can be called in advanced mode with only `advancedQuery` as a parameter
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed changes (if …

fix: correct the call for fields in advanced mode

---

src/resources/Projects/ProjectInterfaces.ts
src/resources/Projects/tests/Project.spec.ts

* Modified the body's attributes to accept an object rather than a list of objects.
See [Swagger](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Workspace#/Projects/rest_organizations_paramId_projects_resources_modify_paramId_put) for more details.
-   [x] My merge commit message will be conventional …

fix(project): modify endpoint body type

---

src/resources/Resource.ts
src/resources/Search/SearchInterfaces.ts
src/resources/Search/test/Search.spec.ts
src/utils/stringifyNestedObjects.ts
src/utils/tests/stringifyNestedObjects.spec.ts

- fix handling of parameters objects that include an object - currently those are not being handled - e.g.
`getFieldValues('ec_name', { commerce: { catalogId: 'id' })` get's serialized as:
`/rest/search/v2/values?field=author&commerce=%5Bobject%20Object%5D`
we want to actually pass those nested params.
This falls in line with how the APIs are expecting the params to get serialized.

fix(project): fix object stringifying

---

package-lock.json
package.json
src/handlers/response/ResponseHandlers.ts
src/handlers/response/tests/ResponseHandlers.spec.ts

JavaScript will automatically round integers that are outside of its "safe" bounds, i.e., from -(2^53 - 1) to 2^53 - 1, inclusive (±9,007,199,254,740,991). This means we'll lose precision if we convert values beyond those boundaries to integers.
The suggested fix is to return out of bound integers as strings, such that no precision will be lost.
Technically, this means that any number in a successful response body will be typed as a number (if it's safe) or as as string (if it's unsafe).
I decided not to adjust the response body interfaces, because this should happen only in a few exceptional cases (e.g., `rowid` / `sysrowid`, which are returned as very large integers).
-   [x] My changes are publicly available, documented, and deployed in production. (i.e. on …

fix(success response handler): parse unsafe integers as strings

---

src/resources/Sources/Sources.ts
src/resources/Sources/tests/Sources.spec.ts

CTCORE-10099
I missed adding it to the Sources interface 😞 

feat(sources): add missing feedback to sources api

---

src/resources/Extensions/Extensions.ts
src/resources/Extensions/ExtensionsInterfaces.ts
src/resources/Extensions/tests/Extensions.spec.ts

Adding methods on the Extension resource for the versions API endpoints:
- listVersions: [`/rest/organizations/{organizationId}/extensions/{extensionId}/versions`](https://platform.cloud.coveo.com/docs/?urls.primaryName=Extension#/Indexing%20Pipeline%20Extensions/rest_organizations_paramId_extensions_paramId_versions_get)
- getVersion: [`/rest/organizations/{organizationId}/extensions/{extensionId}/versions/{versionId}`](https://platform.cloud.coveo.com/docs/?urls.primaryName=Extension#/Indexing%20Pipeline%20Extensions/rest_organizations_paramId_extensions_paramId_versions_paramId_get)
-   [ ] JSDoc annotates each property added in the exported …

feat(extensions): add listVersions and getVersion methods

---

src/resources/Catalogs/CatalogContent.ts
src/resources/Catalogs/CatalogInterfaces.ts
src/resources/Catalogs/tests/CatalogContent.spec.ts

Added new MetadataNames paged call (catalog content)

feat: add new paged metadataNames call

---

.github/workflows/dependency-review.yml

feat: **Target ubuntu-latest directly when running dependency-review **
https://coveord.atlassian.net/browse/DT-7006
Summary of changes:
- The `dependency-review` workflow now targets `ubuntu-latest` directly instead of using the default.
We are changing the default value of the `dependency-review` action to target our self-hosted runners.
Therefore, public repositories must be adjusted prior else they will not be able to run the workflow anymore.
*You should adjust and merge this pull request yourself if you're OK with it. 
Feel free to comment if there's an issue!*

refactor(actions): target ubuntu-latest explicitely when running depency-review [DT-7006]

---

src/resources/Organizations/Organization.ts
src/resources/Organizations/OrganizationInterfaces.ts
src/resources/Organizations/tests/Organizations.spec.ts

The organization has a new property (non-optional) called configuration which contains the boolean property `servingExperiementsAllowed`
The goal is to start leveraging the new property from the org and the new endpoint that was created to update that property.
- Added the property to the organization definition
- (breaking change) Removed the old entrypoint for `getExperimentalStatus`
- Switched over the existing update call to leverage the new endpoint
- Change the default from false to true since we don't promote false.
- …

refactor(organization): leverage organization property for servingExperimentsAllowed

---

src/resources/Sources/SourcesSubInterfaces/Information.ts

[The source service](https://platformdev.cloud.coveo.com/docs?urls.primaryName=Source#/Sources/rest_organizations_paramId_sources_get) adds 2 new attributes (activityId & createdDate) to the `sourceStatus` attribute to be aware of current activity.
-   [ ] My merge commit message will be conventional (See …

feat(source): added new attributes for the SourceStatus interface - CTCORE-10153

---

src/resources/Enums.ts
src/resources/Pipelines/Statements/StatementsInterfaces.ts

Add the `subFeature` query parameter to the `ListStatementParams` interface.
That parameter is properly documented in Swagger [here](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Statements%20V2/listQueryPipelineStatementsV2). 📖 

feat(statements): add subFeature parameter to ListStatementParams

---

src/resources/AnalyticsAdmin/Properties/Properties.ts
src/resources/AnalyticsAdmin/Properties/PropertiesInterfaces.ts
src/resources/AnalyticsAdmin/Properties/index.ts
src/resources/AnalyticsAdmin/index.ts
src/resources/AnalyticsAdmin/tests/Properties.spec.ts
src/resources/PlatformResources.ts
src/resources/index.ts

Added definitions for list, get, create, update and delete properties
[UA-9179]: https://coveord.atlassian.net/browse/UA-9179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

feat(UA-9179): add properties endpoints to client

---

package-lock.json
src/resources/UsageAnalytics/Read/DataHealth/DataHealth.ts
src/resources/UsageAnalytics/Read/DataHealth/DataHealthInterfaces.ts
src/resources/UsageAnalytics/Read/DataHealth/tests/DataHealth.spec.ts

feat(UA-9134): added the getFailedInstances call in the datahealth resource
Ref to the call: https://platformdev.cloud.coveo.com/docs?urls.primaryName=Usage%20Analytics%20Read#/Data%20Health%20API%20-%20Version%2015/get__v15_datahealth_criteria_failedInstances
The call is being used in admin-ui for almost a year now.
-   [x] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) is adjusted to reflect the proposed changes (if …

feat(UA-9134): added the getFailedInstances call in the datahealth resource

---

CODEOWNERS

Adds codeowners for resources owned by data platform (specifically the UI subset of owners).

feat: add codeowners for data platform resources [UA-9391]

---

src/resources/InProductExperiences/InProductExperiences.ts
src/resources/InProductExperiences/InProductExperiencesInterfaces.ts
src/resources/InProductExperiences/tests/InProductExperiences.spec.ts
src/resources/Projects/ProjectInterfaces.ts

[TSP-414](https://coveord.atlassian.net/browse/TSP-414)
Reverts coveo/platform-client#858
After some discussions, it was decided that these calls should be private and not exposed to clients
[TSP-414]: https://coveord.atlassian.net/browse/TSP-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "feat(TSP-414): add listByProject endpoint to platform client"

---

src/resources/Enums.ts
src/resources/UsageAnalytics/Read/Exports/Exports.ts
src/resources/UsageAnalytics/Read/Exports/ExportsInterfaces.ts
src/resources/UsageAnalytics/Read/Exports/tests/Exports.spec.ts

Adds the exports with body endpoints from the experimental client in the admin UI here- https://github.com/coveo-platform/admin-ui/blob/135ef77c0705b5c1925ae4df511bae2fc8637571/core/api/src/resources/UAExportsResource.ts
These endpoints are stable, publicly available and on Swagger, and documented.
-   [x] My …

feat: add exports with a request body [UA-8951]

---

src/resources/UsageAnalytics/Read/Snowflake/Snowflake.ts
src/resources/UsageAnalytics/Read/Snowflake/SnowflakeInterfaces.ts

fix(UA-9417): make daysToExpiry param optional + add response model

---

src/resources/Projects/Project.ts
src/resources/Projects/tests/Project.spec.ts

A scan on github was done to check if this call is used and only SearchApi is using it. Outside of coveo, this call is not used. It was already dropped in the backend.
**Note** This is a breaking change, but the call is not used in PROD/HIPAA …

fix(SRC-5281): drop call that was removed

---

src/resources/Extensions/Extensions.ts
src/resources/Extensions/ExtensionsInterfaces.ts

https://coveord.atlassian.net/browse/SEARCHAPI-11196
I added the `useVault` parameter to the `ExtensionModel` interface. It is publicly documented [here](https://platform.cloud.coveo.com/docs?urls.primaryName=Extension#/Indexing%20Pipeline%20Extensions/rest_organizations_paramId_extensions_paramId_get).
I took the opportunity to refactor the interfaces a bit and added missing documentation on some types and methods.
-   [ ] …

feat(extensions): add missing parameter + JSDoc to Extensions

---

renovate.json
src/resources/ApiKeys/ApiKeys.ts
src/resources/ApiKeys/ApiKeysInterfaces.ts
src/resources/ApiKeys/test/ApiKeys.spec.ts

Improved the type of the `ApiKey.create` call, it now only allow the parameters the backend accept
Added the `lifetimeDuration` parameter

feat(api key): add lifetimeDuration parameter and split interface

---

src/resources/ApiKeys/ApiKeys.ts
src/resources/ApiKeys/test/ApiKeys.spec.ts

Add endpoints for bulk delete, bulk activate, and bulk disable on API keys resource.

feat(api-keys): add endpoints for bulk operations

---

src/resources/License/LicenseInterfaces.ts

https://coveord.atlassian.net/browse/ORG-775
Adding shouldShowInConsumptionDashboard to EntitlementModel

feat(api-keys): adding should show in consumption dashboard to entitlement model

---

src/resources/ApiKeyTemplate/ApiKeyTemplate.ts

Coming from this [PR](https://github.com/coveo/platform-client/pull/889). The first implementation did not correctly set the baseURL. This pr fixes it (by adding `/rest/organizations/:orgId`. …

fix(api-key): fix baseurl

---

src/resources/MachineLearning/ModelDetailedInfo/details/ModelDetailsBuildingStats.ts
src/resources/MachineLearning/ModelDetailedInfo/details/ModelDetailsStatsPerSource.ts

New properties with more specific names are now available for consumption by CPR models
The list of property changes can be seen here:
There's an open PR with the changes from the BE but since they're all optional this PR can go first and will unblock working in the adui.
https://github.com/coveo-platform/ml-config-service/pull/2415
Technically they're already in production on swagger and can be seen on existing models, the addition of it in mlconfig only allows the adui to consume the properties from our own definitions
Not applicable, we do not document these properties as can …

feat(modeldetails): add modelDetails for CPR

---

src/resources/Pipelines/StatementGroups/StatementGroupsInterfaces.ts

[SEARCHAPI-11324](https://coveord.atlassian.net/jira/software/c/projects/SEARCHAPI/boards/1092?quickFilter=3461&selectedIssue=SEARCHAPI-11324)
Add new `conditionDetailed` property in the `StatementGroup` model.
It was added in the backend as you can see in [Swagger](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Statement%20groups/listStatementGroups).
**Note:** it is currently typed as `any` as the other places where the "detailed" condition object is returned. The API doesn't provide a definitive type yet but it is currently being worked on. Once the API defines the schema, I'll update `platform-client` to add the proper interfaces.
-   [ ] My changes are publicly available, documented, and deployed in production. (i.e. on …

feat(statement-groups): add conditionDetailed property

---

src/resources/MachineLearning/ModelDetailedInfo/details/ModelDetails.ts

Property was wrongly baptised, expected property name is 
Technically it's not a breaking change since the property mapped to nothing before, and so changing the name doesn't break the change since nothing points to nothing …

fix(modeldetails): renamed the property to the expected value

---

src/resources/ApiKeys/ApiKeysInterfaces.ts
src/resources/Enums.ts

feat: add exposure report to api key model

---

.github/workflows/ci.yml
package.json
src/resources/ApiKeys/ApiKeysInterfaces.ts
src/resources/Enums.ts
src/resources/License/LicenseInterfaces.ts

I realized the the CI is somehow not linting files anymore or running prettier, which lead to PRs with faulty code style being merged in the master branch.
This PR does the following:
1. Add back lint during CI
2. Lint fix the whole repo
3. Remove eslint from the lint-staged process. Since we lint in the CI anyways, we don't need to slowdown the pre-commit hook too much.
-   [ ] [README.md](https://github.com/coveo/platform-client/blob/master/README.md) …

ci(lint): fix CI workflow not linting files

---

src/resources/MachineLearning/UserActionHistoryConfiguration/UserActionHistoryConfiguration.ts

The user action history is not used anymore in admin-ui, so it is marked as deprecated

feat(MLX): deprecated UserActionHistory class

---

src/resources/ApiKeys/ApiKeysInterfaces.ts

feat: export the exposure report interface

---

src/resources/MachineLearning/ModelDetailedInfo/details/ModelDetailsPreparationDetails.ts

After introduction it was discovered that this property has a typo. It is gramatically incorrect but the current value is indeed `facetsDetails` and not `facetDetails`.
The property has a high cost and impact to rename so the Service team won't rename it anytime soon. To make things work we need to match their property name.
https://github.com/coveo-platform/ml-config-service/pull/2456
-   [x] [README.md](https://github.com/coveo/platform-client/blob/mas …

fix(modeldetailspreparationdetails): match ML Requirements

---

src/resources/MachineLearning/MachineLearning.ts
src/resources/MachineLearning/ModelAssociations/ModelAssociations.ts
src/resources/MachineLearning/ModelAssociations/ModelAssociationsInterfaces.ts
src/resources/MachineLearning/ModelAssociations/index.ts
src/resources/MachineLearning/ModelAssociations/tests/ModelAssociations.spec.ts
src/resources/MachineLearning/index.ts
src/resources/MachineLearning/tests/MachineLearning.spec.ts

Add the model associations call
https://platform.cloud.coveo.com/docs?urls.primaryName=Machine%20Learning%20Configuration#/Model%20Associations/rest_organizations_paramId_machinelearning_configuration_querypipelines_paramId_associations_get …

feat(mlx): add the modelassociations call

---

src/resources/AnalyticsAdmin/Properties/PropertiesInterfaces.ts

We're in the process of making tracking Id nullable, this is just a small PR so that the analytic admin service API interface reflect this change. 

feat(UA-9879): changed the type of tracking ids to (string | null)

---

src/resources/MachineLearning/ModelDetailedInfo/details/ModelDetails.ts

[Disable Content Recs language by default](https://coveord.atlassian.net/browse/COREAI-941)
There is a PR in admin-ui to remove the use of this value : https://github.com/coveo-platform/admin-ui/pull/13906 …

feat(mlx): add deprecation warning for RecommendationsPerLanguage in platform-client

---

src/resources/AnalyticsAdmin/Properties/PropertiesInterfaces.ts

feat(UA-9955): added the includeDefault param to the list properties call
Small update to add the new `incluideDefault` param to our properties list call.
The parameter can be seen here in Swagger: https://platform.cloud.coveo.com/docs?urls.primaryName=Analytics%20Admin%20Service
-   [x] My merge commit message …

feat(UA-9955): added the includeDefault param to the list properties call

---

src/resources/Enums.ts
src/resources/Sources/Sources.ts
src/resources/Sources/SourcesInterfaces.ts
src/resources/Sources/tests/Sources.spec.ts

CTCORE-10773 [Doc Config] Add default document config call to Platform Client
This adds a call to get the default document configuration (`/rest/organizations/{organizationId}/sources/document/configuration/default`) …

feat(source): add call to get default document config

---

src/resources/AnalyticsAdmin/Properties/PropertiesInterfaces.ts

[…](feat:(UA-9904): changes the type of the tracking id from string to string | null)
Made the Tracking Id nullable. Changes in the UI have already been made to account for this change.

feat(UA-9904): changes the type of the tracking id from string to string | null

---

src/resources/Enums.ts

Update the `SecurityProviderType` enum to match the values of the [SecurityProviderType](https://github.com/coveo-platform/security-cache-service/blob/main/coveo-cloud-services-securitycache-api/src/main/java/com/coveo/cloud/securityprovider/model/SecurityProviderType.java) in the security-cache-service 
-   [ ] …

feat: update the SecurityProviderType enum in platform-client

---

src/resources/MachineLearning/MachineLearningInterfaces.ts
src/resources/MachineLearning/ModelAssociations/ModelAssociationsInterfaces.ts
src/resources/MachineLearning/ModelDetailedInfo/ModelDetailedInfoInterfaces.ts
src/resources/MachineLearning/ModelListing/ModelListingInterfaces.ts

Update to add `activeModelBuildDate` in `MLModelStatusInfo`, added in 3 interfaces listing, detailed, and modelassociation 

feat(mlx): update platform-client to add activemodelbuilddate in modelstatusinfo

---

src/resources/ApiKeys/ApiKeysInterfaces.ts

feat: add reasons to exposure report object

---

src/resources/MachineLearning/ModelDetailedInfo/details/ModelDetailsBuildingStats.ts

Adding addToCart and addPurchase
Same thing as the other properties. No documentation, 
Sister PR : https://github.com/coveo-platform/ml-config-service/pull/2536

feat(modeldetailsbuildingstats): added two properties for ART for commerce

---

src/resources/Global/OrganizationConfigurations/OrganizationConfigurationInterfaces.ts

Add missing properties in interface `OrganizationConfigurationModel`.
See it in [Swagger](https://platform.cloud.coveo.com/docs?urls.primaryName=Organization#/Organization%20Global%20Configuration/rest_global_organizations_paramId_get). 📖 
⚠️ **Note:** This schema is not documented in Swagger or in the [official documentation](https://docs.coveo.com/en/3433/api-reference/organization-api#tag/Organization-Global-Configuration/operation/getOrganizationGlobalConfiguration) so no JSDoc was added.
- **_See note above_** 
- _**Not …

feat(organization): add missing properties in OrganizationConfigurationModel

---

src/resources/ApiKeys/ApiKeysInterfaces.ts

* reason and url are optional in new `reasons` field
* reason field of exposure report is now irrelevant
-   [x] My merge commit message will follow the commit guidelines (See [Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines))

fix: reason doesnt exist anymore + reason and url are optional

---

src/resources/Enums.ts
src/resources/SecurityCache/SecurityCacheInterfaces.ts

Move the enum SecurityProviderStatusType in platform-client to delete the[ enum in admin-ui](https://github.com/coveo-platform/admin-ui/blob/master/pages/security-cache/src/constants/SecurityCacheConstants.ts)
-   [ ] My merge commit message will follow the commit guidelines (See [Commit …

feat(security-cache): move the enum SecurityProviderStatusType in platform-client

---

src/resources/AnalyticsAdmin/Properties/Properties.ts
src/resources/AnalyticsAdmin/Properties/PropertiesInterfaces.ts
src/resources/AnalyticsAdmin/tests/Properties.spec.ts

UA-10349
In request of the Workspace team, support for projects was added to the Analytics Admin Service. Properties (effectively tracking IDs) are resources that can be linked to projects, and the service has been updated to work with this. In short, the "list properties" endpoint has these optional filter properties added: `projectId`, `includeProjectIds` & `trackingIds`.
The use case for filtering the list result with `trackingIds` is somewhat obscure, Workspace wants to use this to validate the properties they have mapped still exist. It's not expected other clients will have use for this, but there is also no need to hide this feature from end users. Since the number of tracking IDs may get large, the service now also supports a POST equivalent of `list`, named `query`. (Yes, this …

feat(analytics-admin): add api additions and align naming

---

.github/workflows/cd.yml

In my last PR I added permissions on the workflow but I added `contents: read` instead of `contents: write` since we create tags and push to the repo. This PR fixes it

chore(cd): missing write permission in workflow
